### ISSUE TITLE
Rename azure.eventhub.Topic to azure.servicebus.Topic

### ISSUE THREAD

**Issue by MariuszKogut** [pulumi/pulumi-azure#210] opened 2019-04-17 14:36 UTC
We are using Azure ServiceBus. Is there a way to create our ServiceBus Resources using Pulumi?

**Comment by lukehoban** [comment] 2019-04-17 16:55
The servicebus resources are apparently misclassified, but are present.  They are available as `new azure.eventhub.Topic()` and other resources within the `eventhub` namespace despite not being part of `eventhub`.

We should fix the namespacing here to correctly match Azure (ideally with deprecations not hard breaks on the existing names).

**Comment by mikhailshilkov** [comment] 2019-05-09 10:17
This also applies to Event Grid which has nothing to do with Event Hubs and yet lives in its namespace. I'm doing the Event Grid triggered function and I hate to add it to `eventhubs` namespace...

Shall I try to fix this issue myself?

**Comment by lukehoban** [comment] 2019-05-09 17:21
The issue is that this will be a breaking change (as the namespace structure is part of the Pulumi identity of resources). 

This is also related to https://github.com/pulumi/pulumi-azure/issues/97 which tracks the broader breaking change we need to make to fix up namespacing. 

As noted in that issue, we have work in progress on a solution for enabling these renaming a without a breaking change. So for no I’d suggest we hold off on any changes for a bit, see if we can land that work, and then ideally make this change later when it won’t force replacements of existing resources.

**Comment by stack72** [comment] 2019-06-06 13:32
I am going to close this issue out and link it with #97 so we can track all of the migrations in that same issue

**Closed by stack72** 2019-06-06 13:32 UTC
