### ISSUE TITLE
Pulumi detects changes where there aren't because state contains additional properties

### ISSUE THREAD

**Issue by boillodmanuel** [pulumi/pulumi-azure#411] opened 2019-10-30 08:12 UTC
Hello,

Pulumi detects changes where as there are not changes in following case : 

1. Create an azure policy from the doc example: https://www.pulumi.com/docs/reference/pkg/nodejs/pulumi/azure/policy/#Definition
(see definition below)
1. Execute it with `pulumi up`
1. Do not change anything and execute it again with `pulumi up` 
    => ❌ Pulumi detects changes in metadata where there aren't (seems caused by json serialization in state)
   ```
    Previewing update (dev):

        Type                        Name                Plan       Info
        pulumi:pulumi:Stack         pulumi-sandbox-dev
    ~   └─ azure:policy:Definition  policy              update     [diff: ~metadata]

    Resources:
        ~ 1 to update
        1 unchanged

    Do you want to perform this update? details
    pulumi:pulumi:Stack: (same)
        [urn=urn:pulumi:dev::pulumi-sandbox::pulumi:pulumi:Stack::pulumi-sandbox-dev]
        ~ azure:policy/definition:Definition: (update)
            [id=/subscriptions/08571114-5747-404e-ba8f-d11897318e2d/providers/Microsoft.Authorization/policyDefinitions/accTestPolicy]
            [urn=urn:pulumi:dev::pulumi-sandbox::azure:policy/definition:Definition::policy]
            [provider=urn:pulumi:dev::pulumi-sandbox::pulumi:providers:azure::default_1_2_0::f0512893-d335-4702-ac3f-41c5451faecd]
        ~ metadata: "{\"category\":\"General\",\"createdBy\":\"a31ac596-605d-4eef-a542-8dac1a2646e1\",\"createdOn\":\"2019-10-30T07:58:53.490811Z\",\"updatedBy\":\"a31ac596-605d-4eef-a542-8dac1a2646e1\",\"updatedOn\":\"2019-10-30T08:00:53.3243899Z\"}" => "    {\n        \"category\": \"General\"\n        }\n      "
    ````

## Definition

```ts
import * as pulumi from "@pulumi/pulumi";
import * as azure from "@pulumi/azure";

const policy = new azure.policy.Definition("policy", {
    displayName: "acceptance test policy definition",
    metadata: `    {
    "category": "General"
    }
  `,
    mode: "Indexed",
    name: "accTestPolicy",
    parameters: `	{
    "allowedLocations": {
      "type": "Array",
      "metadata": {
        "description": "The list of allowed locations for resources.",
        "displayName": "Allowed locations",
        "strongType": "location"
      }
    }
  }
`,
    policyRule: `	{
    "if": {
      "not": {
        "field": "location",
        "in": "[parameters('allowedLocations')]"
      }
    },
    "then": {
      "effect": "audit"
    }
  }
`,
    policyType: "Custom",
});
```

**Comment by mikhailshilkov** [comment] 2019-11-18 09:34
@stack72 It's not just formatting: in the example above, several new fields are added by Azure.

@boillodmanuel I suppose you'd have to either change your metadata string to match exactly what Azure returns or add `, {ignoreChanges: ["metadata"]}` to the resource definition to ignore this diff.

**Comment by boillodmanuel** [comment] 2019-11-18 10:04
If I update the `metadata` value, its works. As it's a stack dependant value, I have to put it in stack config.
IMH , it's a better workaround than ignoring changes for that attribute.

If I remove the `metadata` attribute, I do not have this issue neither.

If you can't do anything else, I guess you can close this issue ;)

**Comment by thomas11** [comment] 2024-04-23 15:30
I couldn't reproduce this anymore just now, with up-to-date Policy sample code and provider. Closing.

**Closed by thomas11** 2024-04-23 15:30 UTC
Labels: kind/bug, resolution/fixed, bug/diff
