### ISSUE TITLE
Adding tags to a VirtualNetwork causes replacement

### ISSUE THREAD

**Issue by thrixton** [pulumi/pulumi-azure#572] opened 2020-05-15 01:21 UTC
When I attempt to add tags to an existing VirtualNetwork, it triggers a replacement instead of just adding the tags.

Update
![image](https://user-images.githubusercontent.com/4625987/82001178-e721b800-969d-11ea-8cc9-77d53d3bb40e.png)

Error
![image](https://user-images.githubusercontent.com/4625987/82001272-26500900-969e-11ea-84f7-6068e8dc0bcd.png)

**Comment by mikhailshilkov** [comment] 2020-05-15 06:07
This is a duplicate of https://github.com/pulumi/pulumi/issues/4260
The workaround is to run `pulumi refresh` after the creation of virtual networks and/or subnets. @thrixton see my comment in that issue and let me know if that helps.

**Comment by TheRubble** [comment] 2022-12-20 09:25
This seems to only work is the resources are in the same stack. I've got a shared stack that has lots of shared resources (a vnet being one of them) and then several other stacks that deploy each microservice.

**Comment by mikhailshilkov** [comment] 2023-08-04 13:44
Closing as a duplicate of #4260. That issue has been closed too, and I don't think there is an action item here. Refresh-by-default is tracked in https://github.com/pulumi/pulumi/issues/2247.

**Closed by mikhailshilkov** 2023-08-04 13:44 UTC
Labels: kind/bug, resolution/duplicate
