### ISSUE TITLE
Changing customData does not register a change in state

### ISSUE THREAD

**Issue by jestrjk** [pulumi/pulumi-azure#440] opened 2020-01-16 15:36 UTC
Hi,

When I create a azure.VirtualMachine, changes to osProfile.customData do not register as changes in state. Reference code below. If I change the message that the server is supposed to display  through setting the serverMessage using `--config serverMessage="NewMessage"` or `pulumi config set serverMessage "NewMessage"`  the change is not registered and the virtual machine is not updated / re-created.

```
const serverMessage = config.get("serverMessage") ?? "Hello, World!"

// Now create the VM, using the resource group and NIC allocated above.
let osProfile: azure.types.input.compute.VirtualMachineOsProfile = {
    computerName: `hostname2`,
    adminUsername: username,
    adminPassword: password,
    customData: `#!/bin/bash\n
        echo "${serverMessage}" > index.html
        nohup python -m SimpleHTTPServer 80 &`,
}

const vm = new azure.compute.VirtualMachine("server-vm", {
    resourceGroupName,
    networkInterfaceIds: [networkInterface.id],
    vmSize: "Standard_B1ls",
    deleteDataDisksOnTermination: true,
    deleteOsDiskOnTermination: true,
    osProfile: osProfile,
    osProfileLinuxConfig: {
        disablePasswordAuthentication: false,
    },
    storageOsDisk: {
        createOption: "FromImage",
        name: "myosdisk1",
    },
    storageImageReference: {
        publisher: "canonical",
        offer: "UbuntuServer",
        sku: "16.04-LTS",
        version: "latest",
    },
});
```

I've tried pulumi.output().apply() of that string, doesn't work either.

**Comment by mikhailshilkov** [comment] 2020-01-17 09:34
This is a dupe of #150 which should be tracked in upstream https://github.com/terraform-providers/terraform-provider-azurerm/issues/148

**Closed by mikhailshilkov** 2020-01-17 09:34 UTC
