### ISSUE TITLE
Refresh the state on a blob created from an archive

### ISSUE THREAD

**Issue by UnoSD** [pulumi/pulumi-azure#831] opened 2021-02-05 18:19 UTC
I understand this may not get fixed here, but would appreciate if it could be taken into account when implementing the storage blob resource in AzureNextGen;

When creating a blob from an archive, on running `pulumi up -r` subsequent times the application crashes with the following error:

`System.InvalidOperationException: Expected Pulumi.AssetOrArchive but got System.String deserializing Pulumi.Azure.Storage.Blob.source`

To reproduce:

```
new Blob("appPackage", new BlobArgs
            {
                AccessTier = "Hot",
                Source = new FileArchive("local path to a folder"),
                StorageAccountName = mainStorage.Name,
                StorageContainerName = deploymentsCntainer.Name,
                Type = "Block",
                Name = "application.zip"
            })
```

and run:

`pulumi up` and then `pulumi up -r` after.

Thank you

**Comment by mikhailshilkov** [comment] 2021-02-05 19:34
By the way, the NextGen's Blob is already merged https://github.com/pulumi/pulumi-azure-nextgen/blob/master/sdk/dotnet/Storage/Latest/Blob.cs to be shipped in the next release. I should give your repro a try there...

**Comment by UnoSD** [comment] 2021-02-05 19:45
thank you @mikhailshilkov , I will as soon as it's on NuGet

**Comment by pgavlin** [comment] 2021-02-16 18:42
Closing as a duplicate of https://github.com/pulumi/pulumi-terraform-bridge/issues/328.

**Closed by pgavlin** 2021-02-16 18:42 UTC
