### ISSUE TITLE
Big delay after changing `publicIpAddressAllocation` to `allocationMethod`.

### ISSUE THREAD

**Issue by oliverholliday** [pulumi/pulumi-azure#184] opened 2019-02-19 10:12 UTC
I got a deprecation warning on the `azure.network.PublicIp` resource for `publicIpAddressAllocation` so I updated the definition to use `allocationMethod` instead. 

Ever since then, each `pulumi up` takes at least 5 minutes. It sits at 'refreshing' on each of my PublicIp resources.

**Comment by lukehoban** [comment] 2019-02-20 23:47
Did you run `pulumi refresh`?  You should not see “refreshing...” during a `Pulumi update`. 

Are you seeing this now consistently, even after doing the update?

**Comment by oliverholliday** [comment] 2019-02-21 10:45
My update script used `pulumi up -r` and I was getting the delay every time. I've done a manual `pulumi up` on its own, and that's now cleared it up and a refresh proceeds properly now without the delay.

**Comment by jen20** [comment] 2019-02-21 18:36
Hi @oliverholliday! I've tried reproducing this, but can't get it to happen on my machine with the latest version of the Pulumi CLI and the latest Azure provider. Here's the steps I took - perhaps you could see if anything is obviously different?

First, statically allocate an IP address using the now-deprecated approach:

```typescript
import * as azure from "@pulumi/azure";

// Create an Azure Resource Group
const resourceGroup = new azure.core.ResourceGroup("resourceGroup", {
    location: "WestUS",
});

const publicIp = new azure.network.PublicIp("an-ip", {
    name: "repro184",

    location: resourceGroup.location,
    resourceGroupName: resourceGroup.name,

    publicIpAddressAllocation: "static",
    
    ipVersion: "IPv4",
    tags: {
        Purpose: "Reproduce azure#184",
    },
});

export const ipAddr = publicIp.ipAddress;
```

Run `pulumi up` for this configuration, then change the program to use the replacement argument (also changing the capitalisation of the value):

```typescript
import * as azure from "@pulumi/azure";

// Create an Azure Resource Group
const resourceGroup = new azure.core.ResourceGroup("resourceGroup", {
    location: "WestUS",
});

const publicIp = new azure.network.PublicIp("an-ip", {
    name: "repro184",

    location: resourceGroup.location,
    resourceGroupName: resourceGroup.name,

    allocationMethod: "Static",

    ipVersion: "IPv4",
    tags: {
        Purpose: "Reproduce azure#184",
    },
});

export const ipAddr = publicIp.ipAddress;
```

I then run `pulumi up -r`, and the program runs at the kind of speed I'd expect - you can see the time the process was running (including my reaction time to hitting yes, which was a few seconds), in the subsequent shell prompt:

```shell
$ Code/pulumi-repro/azure-184 pulumi up -r
Previewing update (dev):

     Type                         Name           Plan
     pulumi:pulumi:Stack          azure-184-dev
     ├─ azure:core:ResourceGroup  resourceGroup
     └─ azure:network:PublicIp    an-ip

Resources:
    3 unchanged

Do you want to perform this update? yes
Updating (dev):

     Type                         Name           Status
     pulumi:pulumi:Stack          azure-184-dev
     ├─ azure:core:ResourceGroup  resourceGroup
     └─ azure:network:PublicIp    an-ip

Outputs:
    ipAddr: "138.91.241.161"

Resources:
    3 unchanged

Duration: 5s

Permalink: https://app.pulumi.com/jen20/azure-184/dev/updates/2

$ Code/pulumi-repro/azure-184                                                                                                                        15s
```

Did you also happen to upgrade the version of the provider at the same time as changing the code? Perhaps there may be something worth exploring in that area.

**Comment by oliverholliday** [comment] 2019-02-21 18:40
Hi, many thanks for checking.

I did update versions as part of the same update:

```
-        "@pulumi/azure": "^0.16.7",
-        "@pulumi/kubernetes": "~0.19.0",
+        "@pulumi/azure": "^0.16.9",
+        "@pulumi/kubernetes": "~0.20.2"
```

**Comment by jen20** [comment] 2019-02-21 18:52
@oliverholliday Hmm curious - making the same version upgrade between steps doesn't seem to make a different locally either. Are you able to tell what version of the SDK the public IP was _first_ created with?

**Comment by oliverholliday** [comment] 2019-02-21 19:06
I was using the following packages when I first created that resource:

```
         "@pulumi/azure": "~0.16.5",
         "@pulumi/kubernetes": "~0.18.0",
         "@pulumi/pulumi": "~0.16.7"
```

The only other thing I can think of is that I have resources dependent on the IP - an ingress and a DNS entry.


```

// create a root DNS zone for all operations endpoints
export const dnsRootZone = new azure.dns.Zone("ops.domain.com", {
    name: "ops.domain.com",
    resourceGroupName: resourceGroup.name
});

// create a static IP within the infrastructure RG so that we can take ownership of the DNS
export const dnsOwnershipIp = new azure.network.PublicIp("dnsOwnershipIp", {
    location: config.location,
    resourceGroupName: resourceGroup.name,
    allocationMethod: "Static"
});

// create a default DNS entry to take ownership of the DNS for letsencrypt purposes
export const defaultDnsEntry = new azure.dns.ARecord("@.ops.domain.com", {
    name: "@",
    records: [dnsOwnershipIp.ipAddress],
    resourceGroupName: dnsRootZone.resourceGroupName,
    ttl: 3600,
    zoneName: dnsRootZone.name
});

```

**Comment by jen20** [comment] 2019-02-21 19:26
I'll try using that version and adding a dependent resource - thanks for the additional information!

**Comment by jen20** [comment] 2019-03-07 19:04
Hi @oliverholliday! I've tried reproducing this using a variety of mechanisms - including the exact provider version path you mentioned - but nothing seems to actually be triggering it at this end. Have you run into it since, or with other resources?

**Comment by oliverholliday** [comment] 2019-03-11 14:52
Ever since doing a non-refresh update I've not had this issue at all.

**Comment by lukehoban** [comment] 2019-03-11 18:19
Closing this out since we don't seem to be able to reproduce the original issue - it's possible there was some Azure issue or connectivity issue at the original root of this - but will be hard to pin that down without a repro.

If others see very slow `refresh` on Azure - please do leave a note here with details and we can re-open if needed.

**Closed by lukehoban** 2019-03-11 18:19 UTC
