### ISSUE TITLE
AKS service principal creation not handling async

### ISSUE THREAD

**Issue by jjcollinge** [pulumi/pulumi-azure#103] opened 2018-09-13 17:14 UTC
When running the [AKS](https://github.com/pulumi/examples/tree/master/azure-ts-aks-helm) example for the first time I got the following error:

```
error: Plan apply failed: containerservice.ManagedClustersClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="ServicePrincipalNotFound" Message="Service principal clientID: ****-****-****-**** not found in Active Directory tenant ****-****-****-****, Please see https://aka.ms/acs-sp-help for more details."
```
When I re-ran `pulumi up` it worked. I believe this is due to the asynchronous nature of AAD service principal creation and propagation rather than a bug in the dependency graph. AAD is a particularly problematic resource and I believe has an SLA of ~2 mins for entity availability. It'd be worth having some validate and retry logic such as that in the Azure CLI (https://github.com/Azure/azure-cli/pull/1499) before returning from the create method.

**Comment by lukehoban** [comment] 2018-09-13 18:04
Looking into this.  It sounds like it may be an issue in the underlying `terraform-provider-azurerm` with some wait logic missing from the resource creation path.

**Comment by lukehoban** [comment] 2018-09-13 21:42
Root cause is https://github.com/terraform-providers/terraform-provider-azurerm/issues/1635.

**Comment by jjcollinge** [comment] 2018-09-14 10:56
@lukehoban thanks, looks like you're right. I see the latest Pulumi azure resources are based on TF 1.13 so they should include the [fix](https://github.com/terraform-providers/terraform-provider-azurerm/pull/1647) TF released in [1.12](https://github.com/terraform-providers/terraform-provider-azurerm/blob/39590d40416245084bc343dbb12bceb2e3429d41/CHANGELOG.md). Do you think their fix didn't actually resolve the underlying issue or am I missing something?

**Comment by lukehoban** [comment] 2018-09-24 15:52
> Do you think their fix didn't actually resolve the underlying issue or am I missing something?

I don't believe there is a fix for terraform-providers/terraform-provider-azurerm#1635 yet.  I believe the fix for https://github.com/terraform-providers/terraform-provider-azurerm/pull/1647 addressed a similar case but for a different API (role assignment, not AKS).

**Comment by lukehoban** [comment] 2018-11-08 00:29
I'm going to close this out - since it is really tracking terraform-providers/terraform-provider-azurerm#1635  in upstream getting fixed/merged and then adopting that into Pulumi.  We expect to be adopting latest providers into Pulumi on a continuous basis in the near term, so will just want to push on the upstream issue to get fixed.

@jjcollinge Feel free to reopen if you'd like to have an issue to track on the Pulumi side - else tracking this in upstream is probably sufficient.

**Comment by lukehoban** [comment] 2019-05-08 18:33
My comment above about this being fixed is incorrect - https://github.com/terraform-providers/terraform-provider-azurerm/issues/1635 is still open.  That said, I believe there is nothing Pulumi-specific we can do here.

The "best current workaround" described there is to sleep for 30 seconds.  That can be done in Pulumi with:

``ts
let adApp = new azuread.Application("aks");
let adSp = new azuread.ServicePrincipal("aksSp", { applicationId: adApp.applicationId });
let adSpPassword = new azuread.ServicePrincipalPassword("aksSpPassword", {
    servicePrincipalId: adSp.id,
    // ...
});
let delayedAdSpPasswordValue = adSpPassword.value.apply(async (val) => {
    // Wait for 30s
    console.log("Waiting for 30s for AD Service Principal eventual consistency...");
    await new Promise(resolve => setTimeout(resolve, 30000));
    return val;
});
let aks = new azure.containerservice.KubernetesCluster("aksCluster", {
    //...
    servicePrincipal: {
        // ...
        clientSecret: delayedAdSpPasswordValue,
    },
});
```

**Closed by lukehoban** 2019-05-08 18:33 UTC
Labels: area/providers, kind/bug

**Comment by mastoj** [comment] 2022-07-11 22:50
@lukehoban, I guess applies to ManagedCluster in azure-native as well? Or is it a fix for it now that I have missed?
