### ISSUE TITLE
Problems updating `AppService.appSettings`

### ISSUE THREAD

**Issue by loic-sharma** [pulumi/pulumi-azure#67] opened 2018-06-17 23:09 UTC
1. It seems updating/adding a value on an `AppService`'s `appSettings` does not work. I get the following error:

```
PS D:\Code\pulumi-test> pulumi update
Previewing update of stack 'pulumi-test'
Previewing changes:

     Type                         Name     Plan       Info
 ~   azure:appservice:AppService  testApp  update     changes: ~ appSettings

info: 1 change previewed:
    ~ 1 resource to update
      7 resources unchanged

Do you want to perform this update? yes
Updating stack 'pulumi-test'
Performing changes:

     Type                         Name     Status                  Info
 ~   azure:appservice:AppService  testApp  **updating failed**     changes: ~ appSettings, 2 errors

Diagnostics:
  azure:appservice:AppService: testApp
    error: Plan apply failed: updating urn:pulumi:pulumi-test::pulumi-test::azure:appservice/appService:AppService::testApp: web.AppsClient#CreateOrUpdate: Failure sending request: StatusCode=409 -- Original Error: failed request: autorest/azure: Service returned an error. Status=<nil> <nil>

    error: update failed

info: no changes required:
      7 resources unchanged

Permalink: https://app.pulumi.com/loic-sharma/pulumi-test/updates/11
error: update failed
```

I can get around this by doing `pulumi destroy` followed by a `pulumi update`.

2. It seems that changing an `AppService`'s `appSettings`'s value from a string to an `Output<string>` doesn't get detected. Example from:

```ts
appSettings: {
  "Hello": "World"
}
```

Example to:

```ts
appSettings: {
  "Hello": all([output1, output2]).apply(([a, b]) => `${a} ${b}`)
}
```

Running `pulumi update` will result in a preview of no changes.

**Comment by lukehoban** [comment] 2018-07-09 19:43
> It seems updating/adding a value on an AppService's appSettings does not work

I've tried to reproduce this, but have not been able to.  Using the example at https://github.com/pulumi/examples/blob/master/azure-ts-appservice/index.ts, I can comment out and uncomment the `APPINSIGHTS_INSTRUMENTATIONKEY` app setting and re-deploy without problems.

Is there a specific App Setting that was causing problems for you?

> It seems that changing an AppService's appSettings's value from a string to an Output<string> doesn't get detected

Similarly, I couldn't repro this.  When I change the value of `ApplicationInsights:InstrumentationKey` from a `string` to an `Output<string>` things appear to work fine:

```
* pulumi:pulumi:Stack: (same)
    [urn=urn:pulumi:luke-azure-appservice::azure-appservice::pulumi:pulumi:Stack::azure-appservice-luke-azure-appservice]
    ---outputs:---
    endpoint: "https://appservice-as3949629e.azurewebsites.net"
    ~ azure:appservice/appService:AppService: (update)
        [id=/subscriptions/0282681f-7a9e-424b-80b2-96babd57a8a1/resourceGroups/appservice-rg2f656cc8/providers/Microsoft.Web/sites/appservice-as3949629e]
        [urn=urn:pulumi:luke-azure-appservice::azure-appservice::azure:appservice/appService:AppService::appservice-as]
      ~ appSettings      : {
          ~ ApplicationInsights:InstrumentationKey: "Hello" => "abcd1234-2151-4ff3-870e-d46573dd4882"
        }
    ---outputs:---
    endpoint: computed<string>
```

For both of these - we may need more details about the specific configuration you were using or the specific app settings that were causing a problem.

**Comment by lukehoban** [comment] 2018-07-09 19:44
Closing for now - but please do provide any additional details that we could use to reproduce this and we can re-open.

**Comment by juchom** [comment] 2018-12-05 16:02
Actually, I just hit the same issue:

First use this index.ts file

```typescript
import * as pulumi from "@pulumi/pulumi";
import * as azure from "@pulumi/azure";

const resourceGroup = new azure.core.ResourceGroup("azuretest", {
    name: "azuretest",
    location: "westeurope",
});

const resourceGroupArgs = {
    resourceGroupName: resourceGroup.name,
    location: resourceGroup.location,
};

const appServicePlan = new azure.appservice.Plan(`azuretest-asp`, {
    ...resourceGroupArgs,
    name: 'azuretest-asp',
    kind: "App",
    sku: {
        tier: "Free",
        size: "F1",
    },
});

const app = new azure.appservice.AppService(`azuretest-web`, {
    ...resourceGroupArgs,
    name: `azuretest-web`,
    appServicePlanId: appServicePlan.id
});

export const webSiteUrl = app.defaultSiteHostname.apply(n => `https://${n}`);
```
Run pulumi up, everything is fine.

Now, let's add to our index.ts file Application Insights and configure it in the App Service

```typescript
import * as pulumi from "@pulumi/pulumi";
import * as azure from "@pulumi/azure";

const resourceGroup = new azure.core.ResourceGroup("azuretest", {
    name: "azuretest",
    location: "westeurope",
});

const resourceGroupArgs = {
    resourceGroupName: resourceGroup.name,
    location: resourceGroup.location,
};

const appServicePlan = new azure.appservice.Plan(`azuretest-asp`, {
    ...resourceGroupArgs,
    name: 'azuretest-asp',
    kind: "App",
    sku: {
        tier: "Free",
        size: "F1",
    },
});

const appInsights = new azure.appinsights.Insights(`azuretest-ai`, {
    ...resourceGroupArgs,
    name: `azuretest-ai`,
    applicationType: "Web"
});

const app = new azure.appservice.AppService(`azuretest-web`, {
    ...resourceGroupArgs,
    name: `azuretest-web`,
    appServicePlanId: appServicePlan.id,
    appSettings: {
        "APPINSIGHTS_INSTRUMENTATIONKEY": appInsights.instrumentationKey
    }
});

export const webSiteUrl = app.defaultSiteHostname.apply(n => `https://${n}`);
```
If you run pulumi up, it will create Application Insights but fails on updating appSettings.

If you run pulumi up a second time, it says it worked but nothing changed in the appSettings.

**Comment by juchom** [comment] 2019-01-02 09:41
Not sure if I have to open a new issue, the bug above was with pulumi 0.16.6 and it is still present with pulumi 0.16.9

**Comment by lukehoban** [comment] 2019-01-14 05:52
I confirmed I can reproduce this, but not sure where the problem ultimately is - the Azure ARM APIs underneath this are very finicky, and it's possible the underlying issue is https://github.com/terraform-providers/terraform-provider-azurerm/issues/1303#issuecomment-435062255 or something similar.  Most likely there is not a Pulumi-specific issue here, and something will need to be addressed in the TF provider to improve things here - but we'll need to investigate further to identify what and to understand workarounds.

**Comment by juchom** [comment] 2019-02-11 15:21
Update on this issue: actually this is not limited to Application Insights but it seems to be on all appSettings update on web app.

ZipDeploy is working fine on Azure Functions but it fails on WebApp.

This is a pretty serious issue, here is a bit of my index.ts file

```ts
let appSettings: any = {                                                       
    "ASPNETCORE_ENVIRONMENT": config.require("aspNetCoreEnvironment"),         
}; 

// blob name is myapp.${BuildNumber}.zip
const signedBlobUrl = signedBlobReadUrl(blob, storageAccount, zipDeployContainer);
appSettings.WEBSITE_RUN_FROM_ZIP = signedBlobUrl;

const app = new azure.appservice.AppService(`azuretest-web`, {
    ...resourceGroupArgs,
    name: `azuretest-web`,
    appServicePlanId: appServicePlan.id,
    appSettings: appSettings
});
```

**Comment by lukehoban** [comment] 2019-02-28 20:28
Given how pervasive use of `AppService` is, this feels important to root cause.

**Comment by juchom** [comment] 2019-03-06 09:01
Here is something interesting:

Changing:

```typescript
const appServicePlan = new azure.appservice.Plan(`azuretest-asp`, {
    ...resourceGroupArgs,
    name: 'azuretest-asp',
    kind: "App",
    sku: {
        tier: "Free",
        size: "F1",
    },
});
```

To

```typescript
const appServicePlan = new azure.appservice.Plan(`azuretest-asp`, {
    ...resourceGroupArgs,
    name: 'azuretest-asp',
    kind: "App",
    sku: {
        tier: "Basic",
        size: "B1",
    },
});
```
Everything works, hope this helps!

**Comment by jen20** [comment] 2019-03-19 18:53
Hi @juchom! Sorry for the delay in responding here. I just tried reproducing this with the latest versions of the Pulumi CLI (v0.17.1) and `pulumi-azure` (v0.17.2), using your detailed (thank you!) AppService example of adding Application Insights. I believe this was one of a class of bugs fixed by @pgavlin's recent work to improve handling of default values.

After running the second part of the example, I see the following in the Azure Portal:

![image](https://user-images.githubusercontent.com/548524/54633530-97b20e80-4a3d-11e9-97f7-9a5175b8d43e.png)

I'll mark this issue as closed since it no longer reproduces - if you spot conditions where it is still an issue, please feel free to re-open!

**Closed by jen20** 2019-03-19 18:53 UTC
Labels: help wanted
