### ISSUE TITLE
[Go] Cannot use StringMap for Tags

### ISSUE THREAD

**Issue by elsesiy** [pulumi/pulumi-azure#460] opened 2020-02-19 19:46 UTC
Hi there,

I'm not able to get the following snippet to work:
```
		rg, err := core.NewResourceGroup(ctx, "testrg", &core.ResourceGroupArgs{
			Tags: pulumi.StringMap{"Key": "TEST"},
		})
```

leads to `./main.go:18:35: cannot use "TEST" (type string) as type pulumi.StringInput in map value:
	string does not implement pulumi.StringInput (missing ElementType method)`.

Changing this to adhere to the type definition:
```
		rg, err := core.NewResourceGroup(ctx, "testrg", &core.ResourceGroupArgs{
			Tags: pulumi.StringMap{"Key": pulumi.String("Test")},
		})
```

leads to `error: program failed: marshaling properties: awaiting input property tags: expected a string, got a []`

Thanks for your support!

**Comment by mikhailshilkov** [comment] 2020-02-20 08:16
@EvanBoyle could you take a look?

**Comment by EvanBoyle** [comment] 2020-02-20 17:27
@elsesiy I'm unable to reproduce this. What version of the CLI and Azure plugin are you using?
```bash
$ pulumi version
$ pulumi plugin ls 
```

**Comment by elsesiy** [comment] 2020-02-20 17:54
`v1.10.1`
`azure  resource  1.14.0   160 MB  1 day ago  1 day ago`

**Comment by EvanBoyle** [comment] 2020-02-20 18:28
This seems to be fixed in the v1.11 version that we're in the process of releasing. Here's a tracking issue: https://github.com/pulumi/pulumi/issues/3940

Once that's out can you upgrade and give this another try?

**Comment by elsesiy** [comment] 2020-02-20 18:33
Ah great, yeah sure thank you!

**Comment by elsesiy** [comment] 2020-02-21 21:47
Hi @EvanBoyle, I just tried it with the new release and it's still not working.
`$ pulumi version
v1.11.0`

Error:
`error: program failed: marshaling properties: awaiting input property tags: expected a string, got a []`

**Comment by EvanBoyle** [comment] 2020-02-22 00:26
Two things to debug here. Can you first run a `dep ensure`, then `pulumi up -v 10 --logtostderr` to get some additional debug information?

**Comment by elsesiy** [comment] 2020-02-22 04:26
Okay I figured it out, my issue was that I was declaring the tags once on the resource group and then tried to reference them from all other resources via `rg.Tags` which leads to this obscure error message. Declaring them once independently works as expected!

**Comment by EvanBoyle** [comment] 2020-02-22 16:53
Ah, ok I have a repro now. This is definitely a bug, I'll look into it. 

```go
package main

import (
	"github.com/pulumi/pulumi-azure/sdk/go/azure/core"
	"github.com/pulumi/pulumi/sdk/go/pulumi"
)

func main() {
	pulumi.Run(func(ctx *pulumi.Context) error {
		rg, _ := core.NewResourceGroup(ctx, "testrg", &core.ResourceGroupArgs{
			Tags:     pulumi.StringMap{"Key": pulumi.String("TEST")},
			Location: pulumi.String("westus2"),
		})

		_, _ = core.NewResourceGroup(ctx, "testrg2", &core.ResourceGroupArgs{
			Tags:     rg.Tags,
			Location: rg.Location,
		})

		return nil
	})
}

```

**Comment by elsesiy** [comment] 2020-02-22 17:58
@EvanBoyle Great, thank you! The workaround I mentioned works for now 👍

**Closed** 2020-02-28 18:01 UTC

**Comment by rjshrjndrn** [comment] 2020-09-08 11:26
@EvanBoyle How to parse this tag from stack file
```yaml
  demo:tags:
    Environment: Development
```
```test.go
type Tags struct {
	Tags map[string]pulumi.String `yaml:"tags"`
}
...
...
server, err := NewVMInstance(ctx, name, &VMInstanceArgs{
  Tags:              pulumi.StringMap(v.Tags), // This part is throwing error 
  // cannot convert v.Tags (variable of type map[string]pulumi.String) to pulumi.StringMap
})

```

**Comment by EvanBoyle** [comment] 2020-09-08 12:42
@rjshrjndrn A StringMap has `pulumi.String` values. you cannot instantiate one with a plain type as you are attempting. You'll need to do something like this:

```go
vmTags:= pulumi.StringMap{}
for k, v := range tags{
 vmTags[k] = pulumi.String(v)
}
```
