### ISSUE TITLE
MetadataUrl missing argument for provider

### ISSUE THREAD

**Issue by elsesiy** [pulumi/pulumi-azure#633] opened 2020-07-13 16:15 UTC
`pulumi-azure v3.12.0` is using `2.18.0` of the terraform provider which introduced a new parameter on the provider called `metadata_url`. This parameter is supposed to be optional but pulumi fails without this argument provided.

```
p, err := azure.NewProvider(ctx, "myprovider", &azure.ProviderArgs{
		MetadataUrl:              pulumi.String("https://management.azure.com/metadata/endpoints?api-version=2019-05-01"), # without explicitly providing this arg pulumi fails
		SubscriptionId:           pulumi.String("11111111-1111-1111-1111-111111111111"),
		TenantId:           pulumi.String("11111111-1111-1111-1111-111111111111"),
		SkipProviderRegistration: pulumi.Bool(true),
})
```

The issue is caused by this change https://github.com/pulumi/pulumi-azure/blob/master/sdk/go/azure/provider.go#L24.

See https://github.com/terraform-providers/terraform-provider-azurerm/issues/7699 for reference

**Comment by stack72** [comment] 2020-07-13 16:22
Sorry @elsesiy 

I will get this fixed up and a new point release of the provider cut!

Paul

**Comment by stack72** [comment] 2020-07-13 16:36
Hi @elsesiy 

As you can see from the upstream issue,  I believe that was actually marked as Required incorrectly - waiting to find out if that's the case

**Comment by elsesiy** [comment] 2020-07-13 16:39
Yeah that's why I filed it against the provider repo initially. Especially since there's a disparity between the docs & code. Thanks!

**Comment by stack72** [comment] 2020-07-13 16:40
I believe the issue is there - I am waiting on Tom coming back and saying if that's the bud - we won't need Pulumi to wait for that to be fixed - I just want to know about the ambiguity

**Closed** 2020-07-13 18:04 UTC
