### ISSUE TITLE
App Service with docker container

### ISSUE THREAD

**Issue by spike008t** [pulumi/pulumi-azure#228] opened 2019-05-02 10:43 UTC
Actually, app service support docker container (single container, docker-compose and k8s).
But I cannot make it works with Pulumi. Is is possible to support it?

I can see terraform manage it.

**Comment by johlrich** [comment] 2019-05-04 11:25
@spike008t  I've been able to do this by setting the `DOCKER_CUSTOM_IMAGE_NAME` application setting on the `azure.appservice.AppService`. If it's behind a custom registry then you also need `DOCKER_REGISTRY_SERVER_URL`, `DOCKER_REGISTRY_SERVER_USERNAME`, `DOCKER_REGISTRY_SERVER_PASSWORD`. 

For multi-container `WEBSITES_WEB_CONTAINER_NAME` controls which container is exposed.

**Comment by spike008t** [comment] 2019-05-16 17:26
@johlrich thanks for your response, I'll give a try and give a feedback

**Comment by mikhailshilkov** [comment] 2019-05-17 06:24
@johlrich Thanks for jumping in! This seems to be a common ask so I'd love to make a new example for this scenario. Do you happen to have some code that I could take as a base? That would be awesome :)

**Comment by johlrich** [comment] 2019-05-17 08:57
@mikhailshilkov  Those settings get added to the appSettings, so something like:

```
const dockerAppService = new azure.appservice.AppService(name, {
  location: appservicePlan.location,
  resourceGroupName: appservicePlan.resourceGroupName,
  appServicePlanId: appservicePlan.id,
  httpsOnly: true,
  siteConfig: {
    alwaysOn: true,
  },
  appSettings: {
    APPINSIGHTS_INSTRUMENTATIONKEY: appinsights.instrumentationKey,
    DOCKER_CUSTOM_IMAGE_NAME: registryArgs.DOCKER_CUSTOM_IMAGE_NAME,
    DOCKER_REGISTRY_SERVER_URL: registryArgs.DOCKER_REGISTRY_SERVER_URL,
    DOCKER_REGISTRY_SERVER_USERNAME: registryArgs.DOCKER_REGISTRY_SERVER_USERNAME,
    DOCKER_REGISTRY_SERVER_PASSWORD: registryArgs.DOCKER_REGISTRY_SERVER_PASSWORD,
    ...appSettings
  },
  tags,
})
```

This bookmark helped me figured this stuff out: https://docs.microsoft.com/en-us/azure/app-service/containers/app-service-linux-faq#custom-containers It also describes other app settings to control ports, change startup timeouts, attach storage.  

This is optional, but if you make your own containers and want to support SSH via the azure portal and kudu then there some container config needed too. It looks like they added a good doc for this now: https://docs.microsoft.com/en-us/azure/app-service/containers/configure-custom-container#enable-ssh 

One bump I hit when figuring this out: I originally tried adding these settings to an existing app service that was deployed via zip and I couldn't get things to work until I deleted and redeployed the app. Not sure if it's a reproducible issue, an unsupported scenario or just something I was doing wrong when figuring this stuff out. I haven't had any issues when using these settings across dozens of fresh deployments though.

**Comment by spike008t** [comment] 2019-05-17 09:22
I want to add some comments about that on what I've seen at the moment when create a new stack.

- When creating the linux AppPlan, if I do not set `preserve: true` on the linux App Plan, all the AppServices belong to this app plan do not have containers settings on the web portal.
- On AppService, 
  - I have to add on siteConfig the field `linuxFxVersion: 'DOCKER|<registry>.azurecr.io/image'`
  - Also need to add on appSettings `WEBSITES_ENABLE_APP_SERVICE_STORAGE: 'false'`

Meet theses conditions, I can see the `container settings` on the azure web portal but the app services is not working... I try to figure out why.

I do have something like this:

```typescript

const appPlan = new azure.appservice.Plan(appPlanName, {
    location: resourceGroup.location,
    resourceGroupName: resourceGroup.name,
    kind: `Linux`,
    sku: {
        size: appPlanSize,
        tier: appPlanTier,
    },
    tags,
    reserved: true,
});

const appService = new azure.appservice.AppService(appServiceName, {
    appServicePlanId: appPlan.id,
    location: appPlan.location,
    resourceGroupName: appPlan.resourceGroupName,
    appSettings: {
      DOCKER_REGISTRY_SERVER_PASSWORD: ``,
      DOCKER_REGISTRY_SERVER_URL: `https://${registry}.azurecr.io`,
      DOCKER_REGISTRY_SERVER_USERNAME: registry,
      WEBSITES_ENABLE_APP_SERVICE_STORAGE: 'false',
      DOCKER_CUSTOM_IMAGE_NAME: `${registry}.azurecr.io/${dockerImage}`,
    },
    siteConfig: {
        alwaysOn: true,
        linuxFxVersion: `DOCKER|${registry}.azurecr.io/${dockerImage}`,
    },
    httpsOnly: true,
    tags,
});
```

**Comment by johlrich** [comment] 2019-05-17 09:36
@spike008t Good call on the plan, I forgot to mention that I also have kind: Linux / reserved: true

Best way I found to troubleshoot startup issues was via the appservice's portal blade by enabling logging in the Diagnostics log tab and then look at the Log stream tab. You should see logs for for it pulling the image, the docker run call and polling for startup before your applications logs appear.

**Comment by spike008t** [comment] 2019-05-17 10:16
Oh in fact thats works.... The issue was by my side, I didn't configure correctly my container... All seems ok for me

**Comment by kennyjwilli** [comment] 2019-05-17 15:16
I also struggled with getting a Linux Docker container to run on App Service. My goal was to write a Pulumi program that ran a custom container by following [this guide](https://docs.microsoft.com/en-us/azure/app-service/containers/quickstart-docker-go). Using the CLI or console UI as a guide was not helpful -- each one names parameters differently and does not align with the actual REST API calls. After many hours of trial and error, here's the working code I came up with. Note that it uploads an image to ACR.

```typescript
import * as pulumi from "@pulumi/pulumi";
import * as azure from "@pulumi/azure";
import * as docker from "@pulumi/docker";

const stackName = pulumi.getStack();

const resourceGroup = new azure.core.ResourceGroup("resource-group", {
    name: stackName,
    location: "West US 2"
});

const registry = new azure.containerservice.Registry("registry", {
    name: stackName.replace(/-/g, ""),
    resourceGroupName: resourceGroup.name,
    sku: "Basic",
    adminEnabled: true
});

const myImage = new docker.Image("image", {
    imageName: pulumi.interpolate`${registry.loginServer}/${stackName}`,
    build: {
        context: "../my-app"
    },
    registry: {
        server: registry.loginServer,
        username: registry.adminUsername,
        password: registry.adminPassword
    }
});

const appPlan = new azure.appservice.Plan("app-plan", {
    resourceGroupName: resourceGroup.name,
    kind: "Linux",
    name: stackName,
    sku: {
        size: "S1",
        tier: "Standard",
        capacity: 2
    },
    reserved: true
});



const myApp = new azure.appservice.AppService("app-service", {
    name: stackName,
    resourceGroupName: resourceGroup.name,
    appServicePlanId: appPlan.id,
    appSettings: {
        WEBSITES_ENABLE_APP_SERVICE_STORAGE: false,
        WEBSITES_PORT: 8080,
        DOCKER_REGISTRY_SERVER_URL: registry.loginServer,
        DOCKER_REGISTRY_SERVER_USERNAME: registry.adminUsername,
        DOCKER_REGISTRY_SERVER_PASSWORD: registry.adminPassword
    },
    siteConfig: {
        linuxFxVersion: pulumi.interpolate`DOCKER|${myImage.imageName}`,
        alwaysOn: true,
        cors: {
            allowedOrigins: ["*"]
        }
    },
});
```

Notes: 
- As said in a comment above, you **must** set `reserved: true` on the `Plan` for the container to be deployed as a Linux Docker app. 

I'd still like to know how to do a few other things: 
- Can I expose multiple ports? (I kinda remember reading that App Service does not support this but not sure)
- How do I get the URL of my app? 
- How would I run two different `AppService`s, one with 2 replicas and the other with 1 replica? 
- How would I place a App Gateway in front of this service?

**Comment by spike008t** [comment] 2019-05-17 15:24
Some answers:

- About multiple ports on an AppService, this is not possible, only 80 and 443 are open.
- To get the URL of your app you can retreive the url on the `defaultSiteHostname` attribute of AppService instance. You can exports the generated values (eg: ```exports.myAppUrl = myApp.defaultSiteHostname.apply(n => `https://${n}`)```), doing so, after deploying, pulumi will display the output exported once deployed.

**Comment by johlrich** [comment] 2019-05-17 16:37
> How would I run two different AppServices, one with 2 replicas and the other with 1 replica?

You can set `perSiteScaling: true` for the `azure.appservice.Plan` to setup the plan for this.

For the app itself, there's unfortunately no way to set the siteconfig's numberOfWorkers via the upstream terraform provider yet AFAIK. Calling the ARM api to update the configuration should allow you to fill that gap for now http://docs.microsoft.com/en-us/rest/api/appservice/webapps/createorupdateconfiguration

**Comment by davidobrien1985** [comment] 2019-05-19 06:13
One thing with this that I'm still struggling with is the fact that in the portal when applying this configuration the "Container Settings" show "Private Registry" and not "Azure Container Registry".
It obviously works, just wondering what setting is responsible for this, as I can't find anything in the config or resources.azure.com .

**Comment by mikhailshilkov** [comment] 2019-05-20 08:31
@davidobrien1985 It seems that the portal expects "Azure Container Registry" URL to start with `https`. If I do this in my Pulumi program:
```
DOCKER_REGISTRY_SERVER_URL: pulumi.interpolate`https://${registry.loginServer}`,
```
then the portal shows the first tab.

**Comment by stack72** [comment] 2019-06-05 11:58
Closed via https://github.com/pulumi/examples/pull/302

**Closed by stack72** 2019-06-05 11:58 UTC
