### ISSUE TITLE
Cannot select .NET Core as runtime stack for App Service

### ISSUE THREAD

**Issue by thomaslundgaard** [pulumi/pulumi-azure#625] opened 2020-07-01 12:32 UTC
Azure App Services now support .NET Core apps on windows (https://azure.microsoft.com/en-us/updates/azure-app-service-net-core-31-ga-on-app-service/).

In the Azure Portal it is possible to choose the runtime stack on the App Service and its slots. I have not been able to configure this through pulumi.

**Comment by mikhailshilkov** [comment] 2020-07-01 12:37
Dupe of #508?

**Comment by thomaslundgaard** [comment] 2020-07-01 16:07
Yes, this is the same issue as #508 

After seeing that issue i have tried to select .NET Framework 4.7 in azure portal and my app still works, even though the app code is .NET Core.

While that is great, it would still give me peace of mind if I could configure this option through pulumi, so I can set it correctly on all my app services.

**Comment by mikhailshilkov** [comment] 2020-07-03 07:46
Have you seen this recent comment? https://github.com/pulumi/pulumi-azure/issues/508#issuecomment-652394641

**Closed** 2020-07-03 07:46 UTC

**Comment by thomaslundgaard** [comment] 2020-07-03 12:10
Setting LinuxFxVersion = "DOTNETCORE|3.1" results in an error on pulumi up:

updating urn:pulumi:testing::XXX::azure:appservice/appService:AppService::XXX: web.AppsClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="BadRequest" Message="The parameter LinuxFxVersion has an invalid value." Details=[{"Message":"The parameter LinuxFxVersion has an invalid value."},{"Code":"BadRequest"},{"ErrorEntity":{"Code":"BadRequest","ExtendedCode":"01007","Message":"The parameter LinuxFxVersion has an invalid value.","MessageTemplate":"The parameter {0} has an invalid value.","Parameters":["LinuxFxVersion"]}}]

**Comment by cirio** [comment] 2022-07-20 08:49
I've the same error with LinuxFxVersion. Any news about this issue? No workaround works at this time.
