### ISSUE TITLE
Azure dnsZones are not being parsed correctly on pulumi refresh

### ISSUE THREAD

**Issue by Deblugger** [pulumi/pulumi-azure#1331] opened 2023-08-11 07:19 UTC
### What happened?

Whenever i try to do a `pulumi refresh` im getting the next error:

`
error: Preview failed: refreshing urn:pulumi:my-stack::infra.pulumi::azure:dns/zone:Zone::my-url.com: 1 error occurred:
    	* parsing "/subscriptions/my-subscription-id/resourceGroups/my-resource-group/providers/Microsoft.Network/dnszones/my-url.com": parsing segment "staticDnsZones": expected the segment "dnszones" to be "dnsZones"
`

### Expected Behavior

i dont get the error

### Steps to reproduce

- Create an azure.dns.Zone object (also works with azure.dns.ARecord)
- Try to perform a pulumi refresh

### Output of `pulumi about`

CLI          
Version      3.78.0
Go Version   go1.20.6
Go Compiler  gc

Plugins
NAME          VERSION
azure         5.41.0
azure-native  1.64.1
azuread       5.40.0
datadog       4.21.0
kubernetes    3.30.2
nodejs        unknown
random        4.13.2

Host     
OS       darwin
Version  13.4
Arch     x86_64

<sensible information>

Found no pending operations associated with my-stack

Backend        
<sensible information>

Dependencies:
NAME                              VERSION
@pulumi/pulumi                    3.77.1
@types/node                       17.0.40
@typescript-eslint/eslint-plugin  6.1.0
@typescript-eslint/parser         6.1.0
eslint                            8.45.0
typescript                        5.1.6
@pulumi/azure-native              1.64.1
@pulumi/kubernetes                3.30.2
eslint-plugin-import              2.26.0
eslint-plugin-simple-import-sort  7.0.0

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by rquitales** [comment] 2023-08-15 21:45
Hello @Deblugger,

We apologize for the inconvenience you're facing. We'd like to help you resolve this error. Could you kindly provide us with a minimal code example that demonstrates the issue you're encountering? This will enable us to reproduce the problem and diagnose the root cause more effectively.

In the meantime, I tested a similar code snippet on my end and didn't encounter the error you described. Here's what I used:

```typescript
import * as pulumi from "@pulumi/pulumi";
import * as azure from "@pulumi/azure";

const resourceGroup = new azure.core.ResourceGroup("resourceGroup", {
    location: "WestUS",
});

const dnsZone = new azure.dns.Zone("dnsZone", {
    resourceGroupName: resourceGroup.name,
    name: "example-pulumi.com",
});

export const zoneName = dnsZone.name;
```

I ran the commands `pulumi up -y` and `pulumi refresh` and didn't face the error. However, it's worth noting that software versions can sometimes play a role in such issues. Given that you're using slightly older versions of `pulumi-azure` and the Pulumi CLI, consider updating to the latest versions to see if that resolves the problem.

Please provide us with the minimal code example and let us know if updating the software versions helps. We're here to assist you in resolving this issue.

**Comment by Deblugger** [comment] 2023-08-30 09:14
I fixed it, i dont know why but the id of the resource contained "dnsZone", the way I fixed that was just export the current stack as a json file, then I replace all "dnsZone" by "dnszone", import it again into the current stack and run again `pulumi refresh`

**Comment by mikhailshilkov** [comment] 2023-09-14 10:11
Since you worked past the issue, I'll go ahead and close it. Thank you for your status update.

**Closed by mikhailshilkov** 2023-09-14 10:11 UTC
Labels: kind/bug, resolution/no-repro, needs-repro
