### ISSUE TITLE
Unavoidable changes to azure.postgresql.Server when upgrading from 3.1.0

### ISSUE THREAD

**Issue by clstokes** [pulumi/pulumi-azure#543] opened 2020-05-02 00:10 UTC
v2.7.0 of the Terraform AzureRM provider moved and deprecated some properties on `azure.postgresql.Server` that cause unavoidable changes when upgrading in Pulumi.

The `storageProfile` properties now exist on the top-level `ServerArgs` object. After upgrading and changing code to match the new properties, Pulumi wants to update an existing Server even though there are no actual changes.

#### Steps to reproduce

1. clone the code below and `npm i`
1. `pulumi up`
1. `npm i @pulumi/azure@3.2.0`
1. comment the `pulumi-azure 3.1.0 and earlier` code and uncomment the `post pulumi-azure 3.1.0` code in `index.ts`
1. `pulumi preview`
    - observe the preview wants to update the server even though nothing has actually changed

#### Code to reproduce 

https://gist.github.com/594c27f11934bdb9b12df88e0db4ca55

**Comment by sfc-gh-jelsesiy** [comment] 2020-05-02 00:12
Thank you @clstokes for filing this!

**Comment by elsesiy** [comment] 2020-05-02 00:13
Thank you @clstokes for filing this!

**Comment by elsesiy** [comment] 2020-05-08 01:37
@stack72 Did you get to take a look at this?

**Comment by elsesiy** [comment] 2020-07-11 04:04
I believe this issue can be closed now @clstokes. We were able to update our instances without issues, looks like it was not an issue caused by pulumi.

**Comment by stack72** [comment] 2020-07-13 16:41
Thanks for the info here @elsesiy 

If you do have a way that you did this then I'd love to hear about it :) I will close this out for now

Paul

**Closed by stack72** 2020-07-13 16:41 UTC
