### ISSUE TITLE
DiagnosticSetting for LoadBalancer shows changes on every up

### ISSUE THREAD

**Issue by muellermatthias** [pulumi/pulumi-azure#930] opened 2021-07-29 09:08 UTC
I'm currently trying to add DiagnosticSettings for my LoadBalancer. Adding them works fine, but on the next *up* Pulumi shows me changes for all log and metric categories although nothing changed.

I tested it with Terraform directly and it works as expected there.
I'm using the latest Pulumi version (3.9.0) and the latest provider version (4.11.0).

## Steps to reproduce

Here is my example code:
```typescript
import * as azure from "@pulumi/azure";

const resourceGroup = new azure.core.ResourceGroup("resourceGroup");

const law = new azure.operationalinsights.AnalyticsWorkspace("test-law", {
    resourceGroupName: resourceGroup.name,
    sku: "PerGB2018",
})

const lb = new azure.lb.LoadBalancer("test", {
    resourceGroupName: resourceGroup.name,
})

new azure.monitoring.DiagnosticSetting("lb", {
    targetResourceId: lb.id,
    logAnalyticsWorkspaceId: law.id,
    logs:[{
        category: "LoadBalancerAlertEvent",
        enabled: true,
    }, {
        category: "LoadBalancerProbeHealthStatus",
        enabled: true
    }],
    metrics: [{
        category: "AllMetrics",
        enabled: true,
    }]
})
```

1. Run pulumi up to create all resources.
2. Run pulumi up again. It will show the following diff:
```
      ~ logs   : [
          ~ [0]: {
                  ~ category: "LoadBalancerAlertEvent" => "LoadBalancerAlertEvent"
                  ~ enabled : true => true
                }
          ~ [1]: {
                  ~ category: "LoadBalancerProbeHealthStatus" => "LoadBalancerProbeHealthStatus"
                  ~ enabled : true => true
                }
        ]
      ~ metrics: [
          ~ [0]: {
                  ~ category: "AllMetrics" => "AllMetrics"
                  ~ enabled : true => true
                }
        ]
```
Applying the change doesn't help or running pulumi up with the *--refresh* option.

Expected: The plan should show no changes.
Actual: See above.

**Comment by Freakazoid182** [comment] 2022-06-28 16:30
Thanks! I'll be doing that as well then 🙂

**Comment by mikhailshilkov** [comment] 2022-12-19 11:50
I tested the repro above with pulumi-azure 5.27.0 today and wasn't able to reproduce the issue anymore. It looks like it may have been fixed upstream. I'll go ahead and close the issue until anyone reports it's still reproducible.

**Closed by mikhailshilkov** 2022-12-19 11:50 UTC
Labels: kind/bug, area/providers, resolution/fixed
