### ISSUE TITLE
Changing tags shows resource replacements in the preview

### ISSUE THREAD

**Issue by mikhailshilkov** [pulumi/pulumi-azure#279] opened 2019-06-13 13:33 UTC
Adding or changing tags to a storage account causes a plan to run `replace` operation on all child resources:

```
 ~   ├─ azure:storage:Account  storage2        update      [diff: +tags]
 +-  └─ azure:storage:Queue    queue222        replace     [diff: ~name,storageAccountName]
```

Previewing adding or changing tags to a resource group:

```
~   ├─ azure:core:ResourceGroup     resourceGroupTest     update      [diff: ~tags]
+-  ├─ azure:appservice:Plan        test-appservice-plan  replace     [diff: ~location,name,resourceGroupName,tags]
+-  ├─ azure:storage:Account        storage2              replace     [diff: ~location,name,resourceGroupName]
+-  └─ azure:appservice:AppService  frontend-01a          replace     [diff: ~appServicePlanId,location,name,resourceGroupName,tags]
```

Details:

```
    +-azure:storage/queue:Queue: (replace)
        [id=https://storage2e304958b.queue.core.windows.net/queue2229680877e]
        [urn=urn:pulumi:dev::azure-play::azure:storage/queue:Queue::queue222]
      ~ name              : "queue2229680877e" => "queue22239a441a7"
      ~ resourceGroupName : "resourcegrouptest0868d9e4" => output<string>
      ~ storageAccountName: "storage2e304958b" => output<string>

    --azure:storage/account:Account: (delete-replaced)
        [id=/subscriptions/ebca75f3-9e5e-4a96-a777-aeeb2777dbde/resourceGroups/resourcegrouptest0868d9e4/providers/Microsoft.Storage/storageAccounts/storage2e304958b]
        [urn=urn:pulumi:dev::azure-play::azure:storage/account:Account::storage2]
```

The actual update seems to do the operation in-place, but the preview is confusing and scary.

**Comment by lukehoban** [comment] 2019-06-13 20:44
This is surprising.

The replaces are being proposed here because the `resourceGroup.name` passed in to the other resources is treated as not being known -presumably because it could in theory have changed as part of the `resourceGroup` update.  But because `name` is a `ForceNew` property, we should be returning back that it is `stable`, and then using this to propagate the known previous value through to use cases.

From logs - the `resourceGroup` does report this as stable:

```
I0613 13:38:22.230318   32746 provider_plugin.go:533] Provider[azure, 0xc001008120].Diff(urn:pulumi:dev::azure279::azure:core/resourceGroup:ResourceGroup::example,/subscriptions/8bafcca2-660a-4459-a503-b785cf317a3a/resourceGroups/example2188891f) success: changes=2 #replaces=[] #stables=[name location] delbefrepl=false, diffs=#[tags tags]
```

But then the next resource seems an `output<string>` unknown value as an input to Diff:

```
I0613 13:38:22.236366   32746 rpc.go:69] Marshaling property for RPC[Provider[azure, 0xc001008120].Check(urn:pulumi:dev::azure279::azure:eventhub/namespace:Namespace::example).olds]: resourceGroupName={example2188891f}
...
I0613 13:38:22.236388   32746 rpc.go:69] Marshaling property for RPC[Provider[azure, 0xc001008120].Check(urn:pulumi:dev::azure279::azure:eventhub/namespace:Namespace::example).news]: resourceGroupName=output<string>{}
```

That seems like a bug in the engine.  cc @pgavlin.

**Comment by lukehoban** [comment] 2019-06-13 20:53
Repro:

```ts
import * as pulumi from "@pulumi/pulumi";
import * as azure from "@pulumi/azure";

// Create an Azure Resource Group
const resourceGroup = new azure.core.ResourceGroup("example", {
    location: "WestUS",
    // tags: {
    //     foo: "bar",
    // }
});

const sbnamespace = new azure.eventhub.Namespace("example", {
    location: resourceGroup.location,
    resourceGroupName: resourceGroup.name,
    sku: "Standard",
});

const sbqueue = new azure.eventhub.Queue("example", {
    resourceGroupName: resourceGroup.name,
    namespaceName: sbnamespace.name,
    enablePartitioning: true,
});
```

Similar `.tf`:

```tf
resource "azurerm_resource_group" "example" {
  name     = "terraform-servicebus"
  location = "West Europe"
  # tags = {
  #     foo = "bar"
  # }
}

resource "azurerm_servicebus_namespace" "example" {
  name                = "tfexsevicebusnamespace"
  location            = "${azurerm_resource_group.example.location}"
  resource_group_name = "${azurerm_resource_group.example.name}"
  sku                 = "Standard"

  tags = {
    source = "terraform"
  }
}

resource "azurerm_servicebus_queue" "example" {
  name                = "tfexservicebusqueue"
  resource_group_name = "${azurerm_resource_group.example.name}"
  namespace_name      = "${azurerm_servicebus_namespace.example.name}"

  enable_partitioning = true
}
```

**Comment by pgavlin** [comment] 2019-08-06 19:10
Terraform's behavior around resource properties is surprising: all resource properties that are not specifically recorded as unknown in the resource diff are treated as unchanging. We believe that this is acceptable behavior for Terraform because it statically plans all resource changes before executing them, and does not re-evaluate dependent interpolations after changes are executed. This means that if any of these properties _do_ in fact change, those changes will not affect other resources until the next apply.

The Pulumi model is fundamentally different: in order to support the execution of arbitrary code based on the values of resource outputs, we require that code that depends on these values be re-executed once they are known. This means that a `pulumi preview` does not necessarily reflect the _exact_ changes that will be enacted at runtime: instead, it is intended to present a conservative estimate of these changes. As such, we treat all property values as unknown if the resource requires a change (whether or not that change is an in-place update or a replacement). Changing this behavior is possible, but does seem like it would be detrimental to the conservative nature of `pulumi preview`.

One option here is to better indicate during the preview that a replacement may not actually take place if the input properties that are _causing_ that replacement are unknown.

**Comment by mikhailshilkov** [comment] 2019-08-06 19:41
@pgavlin what about the fact of `name` being "stable" as @lukehoban explained above?

Imagine an AKS cluster being a part of that resource group: replace will look super scary in that situation. Even if a general solution doesn't make sense, I'd consider finding a way to prevent the most obvious issues like the one described.

**Comment by pgavlin** [comment] 2019-08-06 19:48
With respect to stables: we don't actually end up using the `stable` list at all (and I'm not sure we ever have). In the long term, I do think that using `stable` to propagate property values will help this scenario out, but it may be too involved for a short term fix.

**Comment by lukehoban** [comment] 2019-09-24 16:09
Closing this out as a dupe of pulumi/pulumi#3190 as these are rooted in the same issue with previews being overly conservative.

**Closed by lukehoban** 2019-09-24 16:09 UTC
Labels: area/core, kind/bug
