### ISSUE TITLE
Panic when updating stack

### ISSUE THREAD

**Issue by juchom** [pulumi/pulumi-azure#383] opened 2019-10-07 08:15 UTC
Using pulumi cli 1.2 and the azure plugin 1.0.0 I can't update my stacks anymore.

Here is the error I have.

```
Updating (my-stack):

     Type                            Name                   Status                  Info
     pulumi:pulumi:Stack             my-project-my-stack  **failed**              1 error; 26 messages
     ├─ azure:storage:Container      zipdeploy                                      1 warning
 ~   └─ azure:appservice:AppService  my-stack-web       **updating failed**     [diff: ~appSettings]; 1 error

Diagnostics:
  azure:storage:Container (zipdeploy):
    warning: urn:pulumi:my-stack::my-project::azure:storage/container:Container::zipdeploy verification warning: "resource_group_name": [DEPRECATED] This field has been deprecate
d and is no longer used - will be removed in 2.0 of the Azure Provider

  azure:appservice:AppService (my-stack-web):
    error: Plan apply failed: transport is closing

  pulumi:pulumi:Stack (my-project-my-stack):
    error: update failed

    panic: interface conversion: interface {} is nil, not map[string]interface {}
    goroutine 67 [running]:
    github.com/pulumi/pulumi-azure/vendor/github.com/terraform-providers/terraform-provider-azurerm/azurerm/helpers/azure.ExpandAppServiceLogs(0x33f20a0, 0xc0000055c0, 0x4, 0x33f20a0, 0xc0000055c0, 0xc000005501)
        /home/travis/gopath/src/github.com/pulumi/pulumi-azure/vendor/github.com/terraform-providers/terraform-provider-azurerm/azurerm/helpers/azure/app_service.go:1258 +0xcb0    github.com/pulumi/pulumi-azure/vendor/github.com/terraform-providers/terraform-provider-azurerm/azurerm.resourceArmAppServiceUpdate(0xc000525b20, 0x33b1960, 0xc000316480, 0x24, 0x74ed780)
        /home/travis/gopath/src/github.com/pulumi/pulumi-azure/vendor/github.com/terraform-providers/terraform-provider-azurerm/azurerm/resource_arm_app_service.go:435 +0x18b5
    github.com/pulumi/pulumi-azure/vendor/github.com/hashicorp/terraform/helper/schema.(*Resource).Apply(0xc0001ed680, 0xc000935450, 0xc000f1c160, 0x33b1960, 0xc000316480, 0x1, 0x0, 0x0)
        /home/travis/gopath/src/github.com/pulumi/pulumi-azure/vendor/github.com/hashicorp/terraform/helper/schema/resource.go:311 +0x26b
    github.com/pulumi/pulumi-azure/vendor/github.com/hashicorp/terraform/helper/schema.(*Provider).Apply(0xc0007a7980, 0xc000ef5840, 0xc000935450, 0xc000f1c160, 0x0, 0x0, 0x0)
        /home/travis/gopath/src/github.com/pulumi/pulumi-azure/vendor/github.com/hashicorp/terraform/helper/schema/provider.go:289 +0x196
    github.com/pulumi/pulumi-azure/vendor/github.com/pulumi/pulumi-terraform/pkg/tfbridge.(*Provider).Update(0xc000528000, 0x4183e60, 0xc00081b800, 0xc0005251f0, 0xc000528000, 0x3571101, 0xc000e74340)
        /home/travis/gopath/src/github.com/pulumi/pulumi-azure/vendor/github.com/pulumi/pulumi-terraform/pkg/tfbridge/provider.go:818 +0xa2b
    github.com/pulumi/pulumi-azure/vendor/github.com/pulumi/pulumi/sdk/proto/go._ResourceProvider_Update_Handler.func1(0x4183e60, 0xc00081b800, 0x384e6e0, 0xc0005251f0, 0x384bb20,0x74ebf68, 0x4183e60, 0xc00081b800)
        /home/travis/gopath/src/github.com/pulumi/pulumi-azure/vendor/github.com/pulumi/pulumi/sdk/proto/go/provider.pb.go:1592 +0x8d
    github.com/pulumi/pulumi-azure/vendor/github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc.OpenTracingServerInterceptor.func1(0x4183e60, 0xc000633ef0, 0x384e6e0, 0xc0005251f0,0xc000e68140, 0xc000e68160, 0x0, 0x0, 0x410b120, 0xc000438920)
        /home/travis/gopath/src/github.com/pulumi/pulumi-azure/vendor/github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc/server.go:57 +0x2eb
    github.com/pulumi/pulumi-azure/vendor/github.com/pulumi/pulumi/sdk/proto/go._ResourceProvider_Update_Handler(0x38a8d40, 0xc000528000, 0x4183e60, 0xc000633ef0, 0xc000934e60, 0xc0006062a0, 0x4183e60, 0xc000633ef0, 0xc000e72000, 0xf5c)
        /home/travis/gopath/src/github.com/pulumi/pulumi-azure/vendor/github.com/pulumi/pulumi/sdk/proto/go/provider.pb.go:1594 +0x15f
    github.com/pulumi/pulumi-azure/vendor/google.golang.org/grpc.(*Server).processUnaryRPC(0xc000053500, 0x41d1c40, 0xc000053e00, 0xc000ee4300, 0xc0005db4d0, 0x74c0b00, 0x0, 0x0, 0x0)
        /home/travis/gopath/src/github.com/pulumi/pulumi-azure/vendor/google.golang.org/grpc/server.go:998 +0x477
    github.com/pulumi/pulumi-azure/vendor/google.golang.org/grpc.(*Server).handleStream(0xc000053500, 0x41d1c40, 0xc000053e00, 0xc000ee4300, 0x0)
        /home/travis/gopath/src/github.com/pulumi/pulumi-azure/vendor/google.golang.org/grpc/server.go:1278 +0xdad
    github.com/pulumi/pulumi-azure/vendor/google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc000427c50, 0xc000053500, 0x41d1c40, 0xc000053e00, 0xc000ee4300)
        /home/travis/gopath/src/github.com/pulumi/pulumi-azure/vendor/google.golang.org/grpc/server.go:717 +0xa6
    created by github.com/pulumi/pulumi-azure/vendor/google.golang.org/grpc.(*Server).serveStreams.func1
        /home/travis/gopath/src/github.com/pulumi/pulumi-azure/vendor/google.golang.org/grpc/server.go:715 +0xa8

Resources:
    4 unchanged

Duration: 12s
```

Let me know if you need more information in order to troubleshoot this issue.

Thanks

**Comment by mikhailshilkov** [comment] 2019-10-07 08:19
@juchom Thanks for reporting this. Could you add the code snippet for your AppService definition?

**Comment by juchom** [comment] 2019-10-07 08:22
Thanks for the quick reply, here is the code for the AppService

```
const appWebName = `app-${env}-web`;
const appWeb = new azure.appservice.AppService(appWebName, {
  ...resourceGroupArgs,
  name: appWebName,
  appServicePlanId: appCommonInfra.getOutput("appServicePlanId"),
  appSettings: appSettings,
  siteConfig: {
    alwaysOn: true
  }
});
```

**Comment by mikhailshilkov** [comment] 2019-10-07 08:29
And what is the value of `appSettings`?

**Comment by juchom** [comment] 2019-10-07 08:32
appSettings is constructed this way in index.ts

```
// At the begining
let appSettings: any = {
  ASPNETCORE_ENVIRONMENT: config.require("aspNetCoreEnvironment")
};

// After Application Insights definition
appSettings.APPINSIGHTS_INSTRUMENTATIONKEY = appInsights.instrumentationKey;

// After the blob upload
appSettings.WEBSITE_RUN_FROM_ZIP = signedBlobUrl;
```

**Comment by mikhailshilkov** [comment] 2019-10-07 08:50
The call stack points to `ExpandAppServiceLogs`. Are you sure you have no `logs` property defined?

**Comment by juchom** [comment] 2019-10-07 08:57
Nothing very special as you can see:

```
const projectName = pulumi.getProject();
const config = new pulumi.Config(projectName);
const env = config.require("env");

const commonInfra = new pulumi.StackReference(
  `mycompany/project/stack-${env}`
);

const resourceGroupArgs = {
  resourceGroupName: commonInfra.getOutput("resourceGroupName"),
  location: commonInfra.getOutput("resourceGroupLocation")
};

let appSettings: any = {
  ASPNETCORE_ENVIRONMENT: config.require("aspNetCoreEnvironment")
};

const appInsightsName = `myproject-${env}-ai`;
const appInsights = new azure.appinsights.Insights(appInsightsName, {
  ...resourceGroupArgs,
  name: appInsightsName,
  applicationType: "Web"
});
appSettings.APPINSIGHTS_INSTRUMENTATIONKEY = appInsights.instrumentationKey;

const appSaName = `project${env}sa`;
const appSa = new azure.storage.Account(appSaName, {
  ...resourceGroupArgs,
  name: appSaName,
  accountKind: "StorageV2",
  accountTier: "Standard",
  accountReplicationType: "LRS"
});

appSettings["AuthorizationServiceConfig:ConnectionString"] =
  appSa.primaryConnectionString;

const zipDeployContainerName = `zipdeploy`;
const zipDeployContainer = new azure.storage.Container(zipDeployContainerName, {
  resourceGroupName: resourceGroupArgs.resourceGroupName,
  storageAccountName: appSa.name,
  containerAccessType: "private",
  name: zipDeployContainerName
});

const buildNumber = process.env.BUILD_BUILDNUMBER;
const fileName = `AppWeb.${buildNumber}.zip`;
let fullFileName = path.resolve(`../dist/${fileName}`);
if (fs.existsSync(fullFileName)) {
  const blob = new azure.storage.Blob("myproject-b", {
    name: fileName,
    source: fullFileName,
    resourceGroupName: resourceGroupArgs.resourceGroupName,
    storageAccountName: appSa.name,
    storageContainerName: zipDeployContainer.name,
    type: "block"
  });

  const signedBlobUrl = signedBlobReadUrl(blob, appSa, zipDeployContainer);
  appSettings.WEBSITE_RUN_FROM_ZIP = signedBlobUrl;
} else {
}

const appWebName = `myproject-${env}-web`;
const appWeb = new azure.appservice.AppService(appWebName, {
  ...resourceGroupArgs,
  name: appWebName,
  appServicePlanId: commonInfra.getOutput("appServicePlanId"),
  appSettings: appSettings,
  siteConfig: {
    alwaysOn: true
  }
});

```

**Comment by mikhailshilkov** [comment] 2019-10-07 09:07
Yeah, this looks very normal. Anything changed just before you got this error for the first time?
Do you get it if you try with a clean stack?
The app is `my-stack-web` in the output and `myproject-${env}-web` in the code. Copy-paste difference?

**Comment by juchom** [comment] 2019-10-07 09:24
Anything changed just before you got this error for the first time? Nothing has changed on the pulumi files for a while. Actually many projects I have are having the same issue.

Do you get it if you try with a clean stack? I've created a clean stack and it worked (The only difference is that the blob is not created because it doesn't exist)

The app is my-stack-web in the output and myproject-${env}-web in the code. Copy-paste difference? Yes

**Comment by juchom** [comment] 2019-10-07 12:04
If this can help, on the new stack, I've changed my index.ts to add a new key to appSettings and I have the same error.

**Comment by mikhailshilkov** [comment] 2019-10-07 13:11
@juchom That's puzzling. Your code still works for me.

Two random things:

1. Could you upgrade the azure provider to 1.2.0 and repost the error stack trace?
2. Could you share for app service plan definition?

**Comment by juchom** [comment] 2019-10-07 13:25
> Could you upgrade the azure provider to 1.2.0 and repost the error stack trace?

I've done pulumi plugin install resource azure 1.2.0 (do I need to do something else after?)

And I have this stacktrace:

```
panic: interface conversion: interface {} is nil, not map[string]interface {}
goroutine 61 [running]:
github.com/pulumi/pulumi-azure/vendor/github.com/terraform-providers/terraform-provider-azurerm/azurerm/helpers/azure.ExpandAppServiceLogs(0x33f20a0, 0xc000e6d580, 0x4, 0x33f20a0, 0xc000e6d580, 0xc000e6d501)
    /home/travis/gopath/src/github.com/pulumi/pulumi-azure/vendor/github.com/terraform-providers/terraform-provider-azurerm/azurerm/helpers/azure/app_service.go:1258 +0xcb0
github.com/pulumi/pulumi-azure/vendor/github.com/terraform-providers/terraform-provider-azurerm/azurerm.resourceArmAppServiceUpdate(0xc000460460, 0x33b1960, 0xc0000cc480, 0x24, 0x74ed780)
    /home/travis/gopath/src/github.com/pulumi/pulumi-azure/vendor/github.com/terraform-providers/terraform-provider-azurerm/azurerm/resource_arm_app_service.go:435 +0x18b5
github.com/pulumi/pulumi-azure/vendor/github.com/hashicorp/terraform/helper/schema.(*Resource).Apply(0xc0002e5680, 0xc000871f40, 0xc000744ba0, 0x33b1960, 0xc0000cc480, 0x1, 0x0, 0x0)
    /home/travis/gopath/src/github.com/pulumi/pulumi-azure/vendor/github.com/hashicorp/terraform/helper/schema/resource.go:311 +0x26b
github.com/pulumi/pulumi-azure/vendor/github.com/hashicorp/terraform/helper/schema.(*Provider).Apply(0xc0007d9980, 0xc0008bb840, 0xc000871f40, 0xc000744ba0, 0x0, 0x0, 0x0)
    /home/travis/gopath/src/github.com/pulumi/pulumi-azure/vendor/github.com/hashicorp/terraform/helper/schema/provider.go:289 +0x196
github.com/pulumi/pulumi-azure/vendor/github.com/pulumi/pulumi-terraform/pkg/tfbridge.(*Provider).Update(0xc00061a000, 0x4183e60, 0xc000b6ac60, 0xc0004edc70, 0xc00061a000, 0x3571101, 0xc000b628c0)
    /home/travis/gopath/src/github.com/pulumi/pulumi-azure/vendor/github.com/pulumi/pulumi-terraform/pkg/tfbridge/provider.go:818 +0xa2b
github.com/pulumi/pulumi-azure/vendor/github.com/pulumi/pulumi/sdk/proto/go._ResourceProvider_Update_Handler.func1(0x4183e60, 0xc000b6ac60, 0x384e6e0, 0xc0004edc70, 0x384bb20, 0x74ebf68, 0x4183e60, 0xc000b6ac60)
    /home/travis/gopath/src/github.com/pulumi/pulumi-azure/vendor/github.com/pulumi/pulumi/sdk/proto/go/provider.pb.go:1592 +0x8d
github.com/pulumi/pulumi-azure/vendor/github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc.OpenTracingServerInterceptor.func1(0x4183e60, 0xc000c56c60, 0x384e6e0, 0xc0004edc70, 0xc000a1c3c0, 0xc000a1c3e0, 0x0, 0x0, 0x410b120, 0xc00044a910)
    /home/travis/gopath/src/github.com/pulumi/pulumi-azure/vendor/github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc/server.go:57 +0x2eb
github.com/pulumi/pulumi-azure/vendor/github.com/pulumi/pulumi/sdk/proto/go._ResourceProvider_Update_Handler(0x38a8d40, 0xc00061a000, 0x4183e60, 0xc000c56c60, 0xc000871c20, 0xc00039c5a0, 0x4183e60, 0xc000c56c60, 0xc000553000, 0xdc5)
    /home/travis/gopath/src/github.com/pulumi/pulumi-azure/vendor/github.com/pulumi/pulumi/sdk/proto/go/provider.pb.go:1594 +0x15f
github.com/pulumi/pulumi-azure/vendor/google.golang.org/grpc.(*Server).processUnaryRPC(0xc0000ab080, 0x41d1c40, 0xc0000ab500, 0xc000c7b200, 0xc0005ff710, 0x74c0b00, 0x0, 0x0, 0x0)
    /home/travis/gopath/src/github.com/pulumi/pulumi-azure/vendor/google.golang.org/grpc/server.go:998 +0x477
github.com/pulumi/pulumi-azure/vendor/google.golang.org/grpc.(*Server).handleStream(0xc0000ab080, 0x41d1c40, 0xc0000ab500, 0xc000c7b200, 0x0)
    /home/travis/gopath/src/github.com/pulumi/pulumi-azure/vendor/google.golang.org/grpc/server.go:1278 +0xdad
github.com/pulumi/pulumi-azure/vendor/google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc000644ae0, 0xc0000ab080, 0x41d1c40, 0xc0000ab500, 0xc000c7b200)
    /home/travis/gopath/src/github.com/pulumi/pulumi-azure/vendor/google.golang.org/grpc/server.go:717 +0xa6
created by github.com/pulumi/pulumi-azure/vendor/google.golang.org/grpc.(*Server).serveStreams.func1
    /home/travis/gopath/src/github.com/pulumi/pulumi-azure/vendor/google.golang.org/grpc/server.go:715 +0xa8
```


> Could you share your app service plan definition?

```
// App Service Plan Creation
const appServicePlanName = `${projectName}-${env}-asp`;
const appServicePlan = new azure.appservice.Plan(appServicePlanName, {
    ...resourceGroupArgs,
    name: appServicePlanName,
    kind: "App",
    sku: {
        tier: "Basic",
        size: "B1",
    },
});
```

**Comment by mikhailshilkov** [comment] 2019-10-07 13:30
> I've done pulumi plugin install resource azure 1.2.0 (do I need to do something else after?)

You actually need to use it in your program. Make sure that the right version is installed, e.g. put this into your `package.json`: 
````
"@pulumi/azure": "^1.2.0",
```` 
and run `npm install` or `yarn install`.

**Comment by juchom** [comment] 2019-10-07 13:34
Thanks for your quick replies, after the npm install, here is the stacktrace:

```
panic: interface conversion: interface {} is nil, not map[string]interface {}
goroutine 61 [running]:
github.com/pulumi/pulumi-azure/vendor/github.com/terraform-providers/terraform-provider-azurerm/azurerm/helpers/azure.ExpandAppServiceLogs(0x350b3e0, 0xc0008caf60, 0x4, 0x350b3e0, 0xc0008caf60, 0xc0008caf01)
    /home/travis/gopath/src/github.com/pulumi/pulumi-azure/vendor/github.com/terraform-providers/terraform-provider-azurerm/azurerm/helpers/azure/app_service.go:1256 +0xcb0
github.com/pulumi/pulumi-azure/vendor/github.com/terraform-providers/terraform-provider-azurerm/azurerm.resourceArmAppServiceUpdate(0xc0004ed110, 0x34ca440, 0xc0000cc480, 0x24, 0x78507a0)
    /home/travis/gopath/src/github.com/pulumi/pulumi-azure/vendor/github.com/terraform-providers/terraform-provider-azurerm/azurerm/resource_arm_app_service.go:434 +0x18b5
github.com/pulumi/pulumi-azure/vendor/github.com/hashicorp/terraform/helper/schema.(*Resource).Apply(0xc0002e1d00, 0xc000a751d0, 0xc00100f580, 0x34ca440, 0xc0000cc480, 0x1, 0x0, 0x0)
    /home/travis/gopath/src/github.com/pulumi/pulumi-azure/vendor/github.com/hashicorp/terraform/helper/schema/resource.go:311 +0x26b
github.com/pulumi/pulumi-azure/vendor/github.com/hashicorp/terraform/helper/schema.(*Provider).Apply(0xc0007fe880, 0xc00100b840, 0xc000a751d0, 0xc00100f580, 0x0, 0x0, 0x0)
    /home/travis/gopath/src/github.com/pulumi/pulumi-azure/vendor/github.com/hashicorp/terraform/helper/schema/provider.go:289 +0x196
github.com/pulumi/pulumi-azure/vendor/github.com/pulumi/pulumi-terraform/pkg/tfbridge.(*Provider).Update(0xc000266000, 0x42eb620, 0xc0004cbd10, 0xc0004ec8c0, 0xc000266000, 0x368ec01, 0xc0013ecb00)
    /home/travis/gopath/src/github.com/pulumi/pulumi-azure/vendor/github.com/pulumi/pulumi-terraform/pkg/tfbridge/provider.go:818 +0xa2b
github.com/pulumi/pulumi-azure/vendor/github.com/pulumi/pulumi/sdk/proto/go._ResourceProvider_Update_Handler.func1(0x42eb620, 0xc0004cbd10, 0x3975e00, 0xc0004ec8c0, 0x3973380, 0x784ef88, 0x42eb620, 0xc0004cbd10)
    /home/travis/gopath/src/github.com/pulumi/pulumi-azure/vendor/github.com/pulumi/pulumi/sdk/proto/go/provider.pb.go:1592 +0x8d
github.com/pulumi/pulumi-azure/vendor/github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc.OpenTracingServerInterceptor.func1(0x42eb620, 0xc0004ca3f0, 0x3975e00, 0xc0004ec8c0, 0xc0013dd780, 0xc0013dd7a0, 0x0, 0x0, 0x4270c00, 0xc00044a900)
    /home/travis/gopath/src/github.com/pulumi/pulumi-azure/vendor/github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc/server.go:57 +0x2eb
github.com/pulumi/pulumi-azure/vendor/github.com/pulumi/pulumi/sdk/proto/go._ResourceProvider_Update_Handler(0x39d34c0, 0xc000266000, 0x42eb620, 0xc0004ca3f0, 0xc000a74eb0, 0xc0005c28a0, 0x42eb620, 0xc0004ca3f0, 0xc001390000, 0xdc5)
    /home/travis/gopath/src/github.com/pulumi/pulumi-azure/vendor/github.com/pulumi/pulumi/sdk/proto/go/provider.pb.go:1594 +0x15f
github.com/pulumi/pulumi-azure/vendor/google.golang.org/grpc.(*Server).processUnaryRPC(0xc0000ab380, 0x433b4c0, 0xc0000ab800, 0xc001386200, 0xc000321e90, 0x7823b00, 0x0, 0x0, 0x0)
    /home/travis/gopath/src/github.com/pulumi/pulumi-azure/vendor/google.golang.org/grpc/server.go:998 +0x477
github.com/pulumi/pulumi-azure/vendor/google.golang.org/grpc.(*Server).handleStream(0xc0000ab380, 0x433b4c0, 0xc0000ab800, 0xc001386200, 0x0)
    /home/travis/gopath/src/github.com/pulumi/pulumi-azure/vendor/google.golang.org/grpc/server.go:1278 +0xdad
github.com/pulumi/pulumi-azure/vendor/google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc0008935f0, 0xc0000ab380, 0x433b4c0, 0xc0000ab800, 0xc001386200)
    /home/travis/gopath/src/github.com/pulumi/pulumi-azure/vendor/google.golang.org/grpc/server.go:717 +0xa6
created by github.com/pulumi/pulumi-azure/vendor/google.golang.org/grpc.(*Server).serveStreams.func1
    /home/travis/gopath/src/github.com/pulumi/pulumi-azure/vendor/google.golang.org/grpc/server.go:715 +0xa8
```

**Comment by mikhailshilkov** [comment] 2019-10-07 14:17
Thanks, I can reproduce it with 1.2 (but not 1.0). Working on a solution...

**Comment by mikhailshilkov** [comment] 2019-10-07 16:05
@pat @lukehoban Please help me diagnose the root cause here.

1. The error is thrown from the TF provider when they try to [convert nil to map](https://github.com/terraform-providers/terraform-provider-azurerm/blob/master/azurerm/helpers/azure/app_service.go#L1253).

2. The `input` parameter of that call is `[map[application_logs:[<nil>] http_logs:[<nil>]]]`, so `logs` map has two properties, both with `nil` values

3. The Pulumi end-program never actually sets `logs` or `applicationLogs` property, so I would expect it to be missing completely.

4. Here is the [TF schema definition](https://github.com/terraform-providers/terraform-provider-azurerm/blob/master/azurerm/helpers/azure/app_service.go#L491).

5. Our state file shows those log propertiese to be empty maps, not nulls: `"logs": { "applicationLogs": {},"httpLogs": {}},`

6. Same is true for `olds` value in [`tfbridge` provider](https://github.com/pulumi/pulumi-terraform/blob/terraform/0.12.8/pkg/tfbridge/provider.go#L779): `logs:{map[applicationLogs:{map[]} httpLogs:{map[]}]}`

7. TF itself doesn't seem to have this bug: probably, it never passes nils in those maps.

8. Pulumi works on the initial `up` but not on `subsequent` up (after the App Service is changed).

Can you tell what goes wrong here?

**Comment by juchom** [comment] 2019-10-08 08:26
Hi @mikhailshilkov,

Just to let you know, the issue is not happening with pulumi/azure 1.0.0, it starts with 1.1.0.

**Comment by pgavlin** [comment] 2019-10-21 20:31
@mikhailshilkov can you gather verbose logs for the problematic update? Depending on the values being sent to the plugin, this could be a bug in the CLI or in the TF bridge.

**Comment by pgavlin** [comment] 2019-10-21 20:31
`-v=10 --logtostderr` would be most helpful.

**Comment by mikhailshilkov** [comment] 2019-10-21 20:56
@pgavlin DMed the log on Slack

**Comment by baoduy** [comment] 2019-10-29 13:08
I got the same issues when added more key to appSettings. However, destroy and re-build from scratch is fine. this is quite a dangerous issue if deploy to Production.

**Comment by mikhailshilkov** [comment] 2019-10-29 14:17
@pgavlin Did you have a chance to look at the debug. The issue is nasty indeed.

**Comment by robertwe** [comment] 2019-11-03 21:01
+1 hit the same problem recently.

**Comment by baoduy** [comment] 2019-11-03 23:52
The workaround solution is add config for appplicatio logs and httpLogs

**Comment by robertwe** [comment] 2019-11-04 14:34
@baoduy thx fir hint but did not work - tested a few times already.

**Comment by gbonventre** [comment] 2019-11-04 17:01
This item is blocking some of our lift and shift from AWS to Azure. Any way to get this resolved sooner?

**Comment by baoduy** [comment] 2019-11-05 01:23
Hi @robertwe 
Here is my code already tried with 3 Azure Subscriptions, and I'm not receive any error after added this code.
```javascript
const storage = new azure.storage.Account(`${name}stg`.toLowerCase(), {
    ...resourceGroupInfo,
   ...
  });

  const container = new azure.storage.Container(`logs`, {
    name: "logs",
    ...
  });

 const webApp = new azure.appservice.AppService(`${name}-web`, {
    ...,
    storageAccounts: [
      {
        accountName: storage.name,
        accessKey: storage.primaryAccessKey,
        name: "storage",
        shareName: "storage",
        type: "AzureBlob"
      }
    ],
    logs: {
      applicationLogs: {
        azureBlobStorage: { level: "Information", retentionInDays: 30, sasUrl: container.id }
      },
      httpLogs: { fileSystem: { retentionInDays: 30, retentionInMb: 100 } }
    }
  });
```

Hope this help.

**Comment by robertwe** [comment] 2019-11-05 08:19
@baoduy I can confirm - this workaround works as expected. Previously I did not add "applicationLogs" just httpLogs. Thx again :)

**Comment by mikhailshilkov** [comment] 2019-11-12 09:02
More people hit this while kicking tyres with .NET... Any progress here @pgavlin ?

**Comment by pgavlin** [comment] 2019-11-12 18:43
Yes--I don't have a fix yet, but I'm beginning to understand what exactly the issue is. In essence this is a problem with our ability to round-trip between TF state and Pulumi state.

**Comment by simonpinn** [comment] 2019-11-14 05:42
👍 hit the same issue here, running through a scenario where I attempt to update the stack after updating a config variable

**Comment by xtellurian** [comment] 2019-11-15 03:25
I had a similar issue that seemed to be triggered later resolved by using `pulumi refresh`

Pulumi version: v1.5.1
@pulumi/azure: 1.4.0

**Comment by Hawxy** [comment] 2019-11-19 02:12
Ran into this same error after adding the below to an app service that already exists:
```csharp
AppSettings =
{
    { "WEBSITE_RUN_FROM_PACKAGE", "1" }
}
```

**Comment by mjwills** [comment] 2019-11-20 20:28
This impacts most of the examples (e.g. https://github.com/pulumi/examples/tree/master/azure-ts-appservice). Initial `pulumi up` works fine, but not subsequent (after changing the html being deployed). `pulumi destroy` then `pulumi up` works fine. 

Might it be worth updating the readme's on the examples in the short term to list the workaround?

**Comment by baoduy** [comment] 2019-11-21 01:15
@mjwills use mime as work around solution until this issues fixed

**Comment by mjwills** [comment] 2019-11-21 10:59
@baoduy My attempt to apply that to the C# sample didn't work, alas (new errors occurred). But thanks for the suggestion. I'll need to wait until it is fixed...

**Comment by mikhailshilkov** [comment] 2019-11-21 11:02
@mjwills .NET has another issue right now https://github.com/pulumi/examples/issues/476

**Comment by baoduy** [comment] 2019-11-22 03:51
@mjwills Ah I see, I haven't tried with C# yet. Seems it is still preview and may have a lot of bugs. However, Typescript quite nice and interesting. I will try C# soon for next project. 

Hope the issue will be soon resolved as it is impact to all across languages.

**Comment by pgavlin** [comment] 2019-11-27 22:46
I believe that the fixes for this have now been released in Pulumi 1.6.1 and `pulumi-azure` 1.5.0.

**Comment by xtellurian** [comment] 2019-11-28 03:44
I just experienced this after updating.
```
panic: interface conversion: interface {} is nil, not map[string]interface {}
    goroutine 222 [running]:
    github.com/terraform-providers/terraform-provider-azurerm/azurerm/helpers/azure.ExpandAppServiceLogs
```

Versions:
Pulumi v1.6.1
azure-1.5.0

**Comment by lukehoban** [comment] 2019-11-28 03:52
Reopening to reconfirm whether this is fixed.

**Comment by mikhailshilkov** [comment] 2019-11-28 09:38
I confirm it's **not** fixed: tried with 1.6.1/1.5.0

**Comment by pgavlin** [comment] 2019-12-02 18:17
Hm. The fix must not have made it into the `pulumi-azure` release.

**Comment by pgavlin** [comment] 2019-12-02 21:28
Okay, I've confirmed this locally with Pulumi 1.6.1 + `pulumi-azure` 1.6.0.

**Closed by pgavlin** 2019-12-02 21:28 UTC
Labels: customer/feedback, kind/bug, priority/P1

**Comment by ustun** [comment] 2020-01-31 13:17
Is this fixed or not? I think not. We are encountering some issues when doing the initial up:

```
 Diagnostics:
  azure:appservice:AppService (toolio-pr5):
    error: transport is closing
 
  azure:appservice:AppService (toolio-pr3):
    error: transport is closing
 
  azure:appservice:AppService (toolio-pr4):
    error: transport is closing
 
  pulumi:pulumi:Stack (toolio-dev-resources-dev):
    panic: interface conversion: interface {} is nil, not map[string]interface {}
    goroutine 59 [running]:
    github.com/terraform-providers/terraform-provider-azurerm/azurerm/helpers/azure.ExpandAppServiceLogs(0x463d320, 0xc000c29320, 0x4, 0x463d320, 0xc000c29320, 0x1)
    	/home/travis/gopath/pkg/mod/github.com/pulumi/terraform-provider-azurerm@v1.41.1-0.20200127185434-ab509a4a12de/azurerm/helpers/azure/app_service.go:1262 +0xc89
    github.com/terraform-providers/terraform-provider-azurerm/azurerm/internal/services/web.resourceArmAppServiceCreate(0xc000464b60, 0x47885c0, 0xc000a28200, 0x0, 0x0)
    	/home/travis/gopath/pkg/mod/github.com/pulumi/terraform-provider-azurerm@v1.41.1-0.20200127185434-ab509a4a12de/azurerm/internal/services/web/resource_arm_app_service.go:300 +0x137f
    github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Resource).Apply(0xc000840500, 0xc000928550, 0xc000ab6a80, 0x47885c0, 0xc000a28200, 0xc000ab6a01, 0x0, 0x0)
    	/home/travis/gopath/pkg/mod/github.com/hashicorp/terraform-plugin-sdk@v1.1.1/helper/schema/resource.go:305 +0x365
    github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Provider).Apply(0xc000840b80, 0xc000c2d6f0, 0xc000928550, 0xc000ab6a80, 0xc000ab6a80, 0x0, 0x0)
    	/home/travis/gopath/pkg/mod/github.com/hashicorp/terraform-plugin-sdk@v1.1.1/helper/schema/provider.go:294 +0x99
    github.com/pulumi/pulumi-terraform-bridge/pkg/tfbridge.(*Provider).Create(0xc000563500, 0x54da000, 0xc000af20c0, 0xc000cdf1c0, 0xc000563500, 0x47daf01, 0xc000cdf6c0)
    	/home/travis/gopath/pkg/mod/github.com/pulumi/pulumi-terraform-bridge@v1.6.4/pkg/tfbridge/provider.go:645 +0x6be
    github.com/pulumi/pulumi/sdk/proto/go._ResourceProvider_Create_Handler.func1(0x54da000, 0xc000af20c0, 0x4ab72e0, 0xc000cdf1c0, 0x4b1d720, 0x7fdf220, 0x54da000, 0xc000af20c0)
    	/home/travis/gopath/pkg/mod/github.com/pulumi/pulumi@v1.9.1/sdk/proto/go/provider.pb.go:1615 +0x86
    github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc.OpenTracingServerInterceptor.func1(0x54da000, 0xc000926c00, 0x4ab72e0, 0xc000cdf1c0, 0xc000ae5ce0, 0xc000ae5d00, 0x0, 0x0, 0x544a340, 0xc0003f32f0)
    	/home/travis/gopath/pkg/mod/github.com/grpc-ecosystem/grpc-opentracing@v0.0.0-20171105060200-01f8541d5372/go/otgrpc/server.go:61 +0x36e
    github.com/pulumi/pulumi/sdk/proto/go._ResourceProvider_Create_Handler(0x4b97260, 0xc000563500, 0x54da000, 0xc000926c00, 0xc000a6f140, 0xc0004bb960, 0x54da000, 0xc000926c00, 0xc000cf5b00, 0xd79)
    	/home/travis/gopath/pkg/mod/github.com/pulumi/pulumi@v1.9.1/sdk/proto/go/provider.pb.go:1617 +0x14b
    google.golang.org/grpc.(*Server).processUnaryRPC(0xc0000ea2c0, 0x552c480, 0xc000563980, 0xc0009f3200, 0xc000910ba0, 0x7fb2170, 0x0, 0x0, 0x0)
    	/home/travis/gopath/pkg/mod/google.golang.org/grpc@v1.24.0/server.go:995 +0x460
    google.golang.org/grpc.(*Server).handleStream(0xc0000ea2c0, 0x552c480, 0xc000563980, 0xc0009f3200, 0x0)
    	/home/travis/gopath/pkg/mod/google.golang.org/grpc@v1.24.0/server.go:1275 +0xd97
    google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc0004670c0, 0xc0000ea2c0, 0x552c480, 0xc000563980, 0xc0009f3200)
    	/home/travis/gopath/pkg/mod/google.golang.org/grpc@v1.24.0/server.go:710 +0xbb
    created by google.golang.org/grpc.(*Server).serveStreams.func1
    	/home/travis/gopath/pkg/mod/google.golang.org/grpc@v1.24.0/server.go:708 +0xa1
 
    error: update failed
 
```

**Comment by pgavlin** [comment] 2020-01-31 17:05
@ustun what version of the `@pulumi/azure` package are you using (assuming you're on NodeJS)?

**Comment by ustun** [comment] 2020-02-01 05:13
@pgavlin Thanks for the swift reply Pat.

My pulumi version is: v1.9.1
My @pulumi/azure version is: @pulumi/azure@1.12.0 

Good news is,  I have been able to circumvent the issue by specifying the following (based on similar suggestions above):

```
logs: {  httpLogs: undefined  }
```

**Comment by mikhailshilkov** [comment] 2020-02-03 09:33
@ustun Thanks, I reproduced the panic. I think it's different enough to warrant a new issue, so I created #454
