### ISSUE TITLE
Deployment causes update of resource while there are no updates

### ISSUE THREAD

**Issue by bascoder** [pulumi/pulumi-azure#965] opened 2021-10-20 14:05 UTC
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

In my Pulumi stack I have an Azure function app with auth settings like:
```cs
var myApp = new FunctionApp(appName, new FunctionAppArgs
{
                AuthSettings = new FunctionAppAuthSettingsArgs
                {
                    // ... my arguments
                }
}
```
This configuration hasn't been changed for 7 months. But somehow during the deployments it applies a change to my resource and shows up in the log:
```
 authSettings               : {
        unauthenticatedClientAction: "RedirectToLoginPage" => ""
    }
```
The above change is applied even when I re-run `pulumi up` multiple times.

This is undesirable because it causes the function app to restart and cause downtime without need. 

### Steps to reproduce

1. Open repository
2. Make no changes
3. Run `pulumi up`
4. Now it applies the change described above

Expected: I expected nothing to happen
Actual: It's updating a resource while there are no updates.

**Comment by mikhailshilkov** [comment] 2023-03-31 09:45
@bascoder I know it's been a very long time since you reported the issue, apologies for that.

If this happens to be an issue for you still, could you please show us what values are set in "my arguments"?

```
AuthSettings = new FunctionAppAuthSettingsArgs
                {
                    // ... my arguments
                }
```

If the issue isn't relevant anymore, let's close it. Thank you!

**Comment by mikhailshilkov** [comment] 2023-07-28 12:28
I'll go ahead and close this issue as stale

**Closed by mikhailshilkov** 2023-07-28 12:28 UTC
Labels: impact/reliability, kind/bug, resolution/no-repro
