### ISSUE TITLE
Changing defaultNodePool in running AKS clusters

### ISSUE THREAD

**Issue by barclayadam** [pulumi/pulumi-azure#819] opened 2021-01-22 12:40 UTC
I've been trying to upgrade the default node pool of a set of AKS clusters using just Pulumi / Terraform without having to do manual work. 

I've read a couple of blog posts that suggest the only way to do this is to create a new node pool manually, delete the default (drain / cordon etc.), and THEN update the Pulumi definition with the new details.

Given that is _is_ possible to "change" the default node pool in AKS, even if not directly in the API, is it possible we would see the ability to change the default node pool within Pulumi in some way? i.e. could it do the creation/drain/delete dance behind the scenes?

If not, is there some recommended steps that could be taken to at least do the manual work through Pulumi? I had thought about:

1. Create a new, differently named node pool as a `KubernetesClusterNodePool` (in System mode). Deploy
2. Change the `defaultNodePool` settings to use the name of this new node pool AND delete the `KubernetesClusterNodePool`

The problem is step 2. Given we delete a Pulumi resource (the "new" node pool), it is going to remove that from the cluster. Having set it to the defaultNodePool does not matter as they are separately controlled resources.

Any suggestions for minimising the manual work here? It's not massively onerous right now as we have to only do this on a single cluster in UAT, but doing it on 10 in production becomes a burden and error prone

**Comment by mikhailshilkov** [comment] 2021-01-22 13:05
@viveklak do you happen to know that?

**Comment by viveklak** [comment] 2021-01-22 17:01
@barclayadam Thanks for the details in the issue. This is a limitation in the azure provider because the cluster is seen as immutable by the provider, see https://github.com/terraform-providers/terraform-provider-azurerm/issues/7093

At the moment the following is a possible workaround with Pulumi:
1. Create a new System node pool with a different name in your program, `pulumi up` to make sure its up
2. Delete the old default nodepool from the Azure console or CLI. Note that AKS will do the draining etc for you so you don't have to manage this as long as the replacement system nodepool is up
3. Change the name for the default nodepol name to the new one and do a `pulumi refresh`. From this point on your state should treat the new nodepool as the default nodepool.

I am going to close this ticket but please reopen if you hit issues.

**Comment by viveklak** [comment] 2021-01-22 17:03
Closing duplicate of https://github.com/pulumi/pulumi-azure/issues/732

**Closed by viveklak** 2021-01-22 17:03 UTC
Labels: kind/question

**Comment by barclayadam** [comment] 2021-01-22 18:59
@viveklak Thank you. It's a shame this is not something that can be achieved, getting the whole thing automated to have to drop back to manual, error-prone work

The above does indeed work, although I added a step to remove the "additional", separate `KubernetesClusterNodePool` resource directly from state so that I did not have a `defaultNodePool` and a separate node pool point to the same thing in AKS. Not sure if necessary, or wise, but it at least puts the resources back in the same shape as before the change.
