### ISSUE TITLE
Terraform error when creating a AnalyticsWorkspace with unlimited dailyQuotaGb

### ISSUE THREAD

**Issue by boillodmanuel** [pulumi/pulumi-azure#806] opened 2021-01-07 13:34 UTC
Since pulumi-azure version 3.31.0, we can not create a `AnalyticsWorkspace` with unlimited `dailyQuotaGb` anymore.

Here is the corresponding code:

```ts
const analyticsWorkspace = new azure.operationalinsights.AnalyticsWorkspace("analyticsWorkspace", {
        name: "law-name",
        resourceGroupName: rg.name,
        retentionInDays: 30,
        sku: "PerGB2018",
})
```

And the corresponding error:
```
Diagnostics:
  azure:operationalinsights:AnalyticsWorkspace (analyticsWorkspace):
    error: azure:operationalinsights/analyticsWorkspace:AnalyticsWorkspace resource 'analyticsWorkspace' has a problem: expected daily_quota_gb to be at least (0.000000), got -1.000000
```

This is due to an update of Terraform AzureRM Provider:v2.36.0, where `log_analytics_workspace` `daily_quota_gb` does not accept anymore the `-1` value to be set explicitly.
If we didn't set the `daily_quota_gb` value, terraform set `-1`, but we can not set `-1` explicitly.
I open an issue on the terraform side https://github.com/terraform-providers/terraform-provider-azurerm/issues/9732, but they close it saying that everything works as expected.

My analysis is that pulumi pass the `-1` value when the value is not set, but terraform does not support it. So we are blocked.

My workaround today is to set a very high value `1000000`.

**Comment by boillodmanuel** [comment] 2021-01-07 16:25
To fix this, I moved this resource to azure next gen, and it works like a charm ;)

**Comment by viveklak** [comment] 2021-01-07 19:13
Looking through we don't seem to override the default here and this seems to be behavior entirely controlled by the terraform provider instead. I suggest reopening the ticket with TF? Closing this for now.

**Closed by viveklak** 2021-01-07 19:13 UTC

**Comment by mikhailshilkov** [comment] 2021-01-07 19:39
@viveklak there was a ticket at TF, see the original report

**Comment by viveklak** [comment] 2021-01-07 20:06
Ah thanks. Marking as duplicate of #784.

**Comment by boillodmanuel** [comment] 2021-01-08 13:23
@viveklak, it's not an issue related to terraform. Terraform works as expected. 

The following Terraform Configuration Files works whereas the corresponding pulumi doesn't.

```hcl
resource "azurerm_resource_group" "rg" {
  name     = "rg-terraform"
  location = "francecentral"
}

resource "azurerm_log_analytics_workspace" "log-aw" {
  name                = "log-tf-01"
  location            = azurerm_resource_group.rg.location
  resource_group_name = azurerm_resource_group.rg.name
  sku                 = "PerGB2018"
  retention_in_days   = 30
}
```

There is no reason to reopen the terraform issue.
