### ISSUE TITLE
Error when adding a slot to a functionapp

### ISSUE THREAD

**Issue by nickvdyck** [pulumi/pulumi-azure#204] opened 2019-03-30 19:06 UTC
I keep running into the following issue when adding a slot to an azure functionapp:

```sh
Updating (dev):

     Type                      Name                          Status                  Info
     pulumi:pulumi:Stack       pulumi-function-app-test-dev  **failed**              1 error
 +   └─ azure:appservice:Slot  function-app-slot             **creating failed**     1 error

Diagnostics:
  azure:appservice:Slot (function-app-slot):
    error: Plan apply failed: web.AppsClient#CreateOrUpdateSlot: Failure sending request: StatusCode=400 -- Original Error: Code="BadRequest" Message="Function App app settings are not expected to be empty. Please try again with WEBSITE_CONTENTAZUREFILECONNECTIONSTRING as a storage account connection string." Details=[{"Message":"Function App app settings are not expected to be empty. Please try again with WEBSITE_CONTENTAZUREFILECONNECTIONSTRING as a storage account connection string."},{"Code":"BadRequest"},{"ErrorEntity":{"Code":"BadRequest","ExtendedCode":"04122","Message":"Function App app settings are not expected to be empty. Please try again with WEBSITE_CONTENTAZUREFILECONNECTIONSTRING as a storage account connection string.","MessageTemplate":"Function App app settings are not expected to be empty. Please try again with {0} as a storage account connection string.","Parameters":["WEBSITE_CONTENTAZUREFILECONNECTIONSTRING"]}}]

  pulumi:pulumi:Stack (pulumi-function-app-test-dev):
    error: update failed
```

I tried a couple of different settings but can't seem to get it to work. It works just fine when adding a slot to an appservice.

The following is a 'small' reproduction of the issue:
```ts
import * as pulumi from "@pulumi/pulumi";
import * as azure from "@pulumi/azure";

// Create an Azure Resource Group
const resourceGroup = new azure.core.ResourceGroup("test-resource-group", {
    location: "West Europe",
});

// Create an Azure resource (Storage Account)
const account = new azure.storage.Account("functionsa", {
    resourceGroupName: resourceGroup.name,
    location: resourceGroup.location,
    accountTier: "Standard",
    accountReplicationType: "LRS",
});

const appServicePlan = new azure.appservice.Plan(
    'function-app-plan',
    {
        resourceGroupName: resourceGroup.name,
        location: resourceGroup.location,
        kind: "FunctionApp",
        sku: {
            tier: "Dynamic",
            size: "Y1",
        },
    },
    { parent: resourceGroup },
)

const functionApp = new azure.appservice.FunctionApp('function-app', {
    resourceGroupName: resourceGroup.name,
    location: resourceGroup.location,
    appServicePlanId: appServicePlan.id,
    storageConnectionString: account.primaryConnectionString,
    appSettings: {
        "test": "test"
    },
    version: "~2"
});

const slot = new azure.appservice.Slot('function-app-slot', {
    name: "staging",
    resourceGroupName: resourceGroup.name,
    location: resourceGroup.location,
    appServiceName: functionApp.name,
    appServicePlanId: appServicePlan.id,
    appSettings: {
        "test": "test",
        "WEBSITE_CONTENTAZUREFILECONNECTIONSTRING": account.primaryConnectionString
    }
});

```

**Comment by mikhailshilkov** [comment] 2019-05-08 09:08
If I read [this](https://github.com/Azure/azure-cli/issues/9126#issuecomment-485883803) and [that](https://github.com/terraform-providers/terraform-provider-azurerm/issues/1307) correctly:

- You can't use App Service slots for Functions
- Neither Azure CLI nor Terraform support Function App slots yet

Functions CLI [doesn't support slots either](https://github.com/Azure/azure-functions-core-tools/issues/227) and the case was once closed as "we're not adding new functionality to slots".

I'm failing to find any docs on Functions v2 explaining the slots support status. [This issue](https://github.com/Azure/Azure-Functions/issues/45) is open and hasn't been updated since 2017.

Doesn't look very optimistic for slots @nickvdyck

**Comment by ColbyTresness** [comment] 2019-05-09 19:29
CC @dariagrigoriu for the actual issue.

To be honest what @mikhailshilkov references is more of a lack of documentation thing than a lack of support thing (which I'm looking at fixing). Slots are actually something we're working on improving. For the dedicated plan, they're GA, and for consumption, preview (hence some bugs which you seem to be running into).

**Comment by JustinGrote** [comment] 2019-05-29 17:16
Looks like https://github.com/Azure/azure-cli/issues/9126 is in progress to fix this for function slots.

**Comment by mikhailshilkov** [comment] 2019-07-19 18:16
I believe we should track https://github.com/terraform-providers/terraform-provider-azurerm/issues/1307 for a fix / a new resource

**Comment by lukehoban** [comment] 2019-07-19 21:50
I’m going to close this out since it’s effectively a dupe of https://github.com/terraform-providers/terraform-provider-azurerm/issues/1307.

**Closed by lukehoban** 2019-07-19 21:50 UTC
