### ISSUE TITLE
'could not load plugin for azure provider' 'failed to locate compatible plugin'.

### ISSUE THREAD

**Issue by oliverholliday** [pulumi/pulumi-azure#200] opened 2019-03-11 15:17 UTC
I had a strange issue this morning where I got the below error message when doing a `pulumi preview` on our CI machine (Ubuntu). I ran the update locally instead on Win10 and it worked ok. Since then the update proceeds normally even on CI.

```
Refreshing state from deployed resources
Refreshing (development):
error: could not load plugin for azure provider 'urn:pulumi:goodfellow-development::goodfellow-development::pulumi:providers:azure::default': failed to locate compatible plugin
WARNING: Pulumi Preview failed.
```

We have a system set up to share state between CI and local updates so they were both operating against the same state files. I'd done a `pulumi refresh` on Win10 before submitting to CI.

The update coincided with pulumi version updates:

```
-        "@pulumi/azure": "^0.16.9",
-        "@pulumi/kubernetes": "~0.20.3",
-        "@pulumi/pulumi": "^0.16.17",
+        "@pulumi/azure": "0.17.1",
+        "@pulumi/kubernetes": "0.21.0",
+        "@pulumi/pulumi": "0.17.1",
```

It seems as if doing a preview on Win10 had prevented the Linux plugin from recognising the provider somehow?

**Comment by lukehoban** [comment] 2019-03-11 15:22
Do you know if you had different versions of NPM packages installed on the local environment and in the CI environment?  Can you share the section of your state file before and after this problem that describes the default Azure provider mentioned in the error message?

**Comment by lukehoban** [comment] 2019-03-11 15:25
@swgillespie looks like this may be related to recent changes to resource provider versioning - do you know what could cause these symptoms?

**Comment by oliverholliday** [comment] 2019-03-11 15:29
When I ran the initial refresh / preview on Win10 the following changes got made to my stack json:

```
                "plugins": [
                    {
                        "name": "nodejs",
                        "path": "/root/.pulumi/bin/pulumi-language-nodejs",
                        "type": "language",
                        "version": "0.16.16"
                    },
                    {
                        "name": "azure",
-                        "path": "/root/.pulumi/plugins/resource-azure-v0.16.9/pulumi-resource-azure",
+                        "path": "C:\\Users\\Oliver Holliday\\.pulumi\\plugins\\resource-azure-v0.16.9\\pulumi-resource-azure.exe",
                        "type": "resource",
                        "version": "0.16.9"
                    },
                    {
                        "name": "kubernetes",
-                        "path": "/root/.pulumi/plugins/resource-kubernetes-v0.20.4/pulumi-resource-kubernetes",
+                        "path": "C:\\Users\\Oliver Holliday\\.pulumi\\plugins\\resource-kubernetes-v0.21.0\\pulumi-resource-kubernetes.exe",
                        "type": "resource",
                        "version": "0.20.4"
                        "version": "0.21.0"
                    }
                ]
```

**Comment by oliverholliday** [comment] 2019-03-11 16:35
Apologies, I've edited the above fragment - the nodejs plugin was removed entirely in that update.

**Comment by swgillespie** [comment] 2019-03-11 18:03
Thanks for the report!

Unfortunately, the error message that the Pulumi CLI emits here is very unhelpful. I'll make a fix for that so that we at least emit the version of the plugin that we are looking for.

If it is possible for you, do you mind running `pulumi preview` with flags `--logtostderr -v 7` and posting the results here? The CLI should log some information about why it is rejecting the plugins that you already have installed (including the 0.16.9 plugin here).

**Comment by swgillespie** [comment] 2019-03-11 18:49
To anyone else having this issue:

You can set the environment variable `PULUMI_ENABLE_LEGACY_PLUGIN_SEARCH=1` to get unblocked and load plugins exactly as before.

**Comment by timmyers** [comment] 2019-03-11 18:52
Here is my output running into the same issue with the `aws` provider:

```
Logging in using access token from PULUMI_ACCESS_TOKEN

Previewing update (dev):

I0311 18:51:44.804079     141 plugins.go:348] GetPluginPath(language, nodejs, <nil>): found on $PATH /root/.pulumi/bin/pulumi-language-nodejs

I0311 18:51:44.804504     141 ignore.go:44] Explicitly ignoring and discarding error: inappropriate ioctl for device

I0311 18:51:44.877588     141 langruntime_plugin.go:166] langhost[nodejs].GetPluginInfo() executing

I0311 18:51:44.877936     141 langruntime_plugin.go:83] langhost[nodejs].GetRequiredPlugins(proj=infrastructure,pwd=/home/jenkins/workspace/infrastructure_master,program=.) executing

I0311 18:51:44.970003     141 langruntime_plugin.go:124] langhost[nodejs].GetRequiredPlugins(proj=infrastructure,pwd=/home/jenkins/workspace/infrastructure_master,program=.) success: #versions=3

I0311 18:51:44.970160     141 registry.go:99] provider(urn:pulumi:dev::infrastructure::pulumi:pulumi:Stack::infrastructure-dev): 

I0311 18:51:44.970240     141 plugins.go:387] GetPluginPath(resource, aws, 0.17.0): enabling new plugin behavior

I0311 18:51:44.970251     141 plugins.go:464] SelectCompatiblePlugin(..., aws): beginning

I0311 18:51:44.970256     141 plugins.go:503] SelectCompatiblePlugin(..., aws): failed to find match

Permalink: https://app.pulumi.com/timmyers/infrastructure/dev/previews/6ed6f315-0bd1-48cf-9294-6d1d8ddad08b

I0311 18:51:45.225986     141 sink.go:154] defaultSink::Error(error: could not load plugin for aws provider 'urn:pulumi:dev::infrastructure::pulumi:providers:aws::default': failed to locate compatible plugin

github.com/pulumi/pulumi/pkg/resource/deploy/providers.NewRegistry

	/home/travis/gopath/src/github.com/pulumi/pulumi/pkg/resource/deploy/providers/registry.go:123

github.com/pulumi/pulumi/pkg/resource/deploy.NewPlan

	/home/travis/gopath/src/github.com/pulumi/pulumi/pkg/resource/deploy/plan.go:227

github.com/pulumi/pulumi/pkg/engine.plan

	/home/travis/gopath/src/github.com/pulumi/pulumi/pkg/engine/plan.go:159

github.com/pulumi/pulumi/pkg/engine.update

	/home/travis/gopath/src/github.com/pulumi/pulumi/pkg/engine/update.go:137

github.com/pulumi/pulumi/pkg/engine.Update

	/home/travis/gopath/src/github.com/pulumi/pulumi/pkg/engine/update.go:88

github.com/pulumi/pulumi/pkg/backend/httpstate.(*cloudBackend).runEngineAction

	/home/travis/gopath/src/github.com/pulumi/pulumi/pkg/backend/httpstate/backend.go:824

github.com/pulumi/pulumi/pkg/backend/httpstate.(*cloudBackend).apply

	/home/travis/gopath/src/github.com/pulumi/pulumi/pkg/backend/httpstate/backend.go:766

github.com/pulumi/pulumi/pkg/backend/httpstate.(*cloudBackend).Preview

	/home/travis/gopath/src/github.com/pulumi/pulumi/pkg/backend/httpstate/backend.go:652

github.com/pulumi/pulumi/pkg/backend.PreviewStack

	/home/travis/gopath/src/github.com/pulumi/pulumi/pkg/backend/stack.go:68

github.com/pulumi/pulumi/pkg/backend/httpstate.(*cloudStack).Preview

	/home/travis/gopath/src/github.com/pulumi/pulumi/pkg/backend/httpstate/stack.go:131

github.com/pulumi/pulumi/cmd.newPreviewCmd.func1

	/home/travis/gopath/src/github.com/pulumi/pulumi/cmd/preview.go:93

github.com/pulumi/pulumi/pkg/util/cmdutil.RunFunc.func1

	/home/travis/gopath/src/github.com/pulumi/pulumi/pkg/util/cmdutil/exit.go:92

github.com/pulumi/pulumi/vendor/github.com/spf13/cobra.(*Command).execute

	/home/travis/gopath/src/github.com/pulumi/pulumi/vendor/github.com/spf13/cobra/command.go:702

github.com/pulumi/pulumi/vendor/github.com/spf13/cobra.(*Command).ExecuteC

	/home/travis/gopath/src/github.com/pulumi/pulumi/vendor/github.com/spf13/cobra/command.go:783

github.com/pulumi/pulumi/vendor/github.com/spf13/cobra.(*Command).Execute

	/home/travis/gopath/src/github.com/pulumi/pulumi/vendor/github.com/spf13/cobra/command.go:736

main.main

	/home/travis/gopath/src/github.com/pulumi/pulumi/main.go:49

runtime.main

	/home/travis/.gimme/versions/go1.11.linux.amd64/src/runtime/proc.go:201

runtime.goexit

	/home/travis/.gimme/versions/go1.11.linux.amd64/src/runtime/asm_amd64.s:1333

)

error: could not load plugin for aws provider 'urn:pulumi:dev::infrastructure::pulumi:providers:aws::default': failed to locate compatible plugin

github.com/pulumi/pulumi/pkg/resource/deploy/providers.NewRegistry

	/home/travis/gopath/src/github.com/pulumi/pulumi/pkg/resource/deploy/providers/registry.go:123

github.com/pulumi/pulumi/pkg/resource/deploy.NewPlan

	/home/travis/gopath/src/github.com/pulumi/pulumi/pkg/resource/deploy/plan.go:227

github.com/pulumi/pulumi/pkg/engine.plan

	/home/travis/gopath/src/github.com/pulumi/pulumi/pkg/engine/plan.go:159

github.com/pulumi/pulumi/pkg/engine.update

	/home/travis/gopath/src/github.com/pulumi/pulumi/pkg/engine/update.go:137

github.com/pulumi/pulumi/pkg/engine.Update

	/home/travis/gopath/src/github.com/pulumi/pulumi/pkg/engine/update.go:88

github.com/pulumi/pulumi/pkg/backend/httpstate.(*cloudBackend).runEngineAction

	/home/travis/gopath/src/github.com/pulumi/pulumi/pkg/backend/httpstate/backend.go:824

github.com/pulumi/pulumi/pkg/backend/httpstate.(*cloudBackend).apply

	/home/travis/gopath/src/github.com/pulumi/pulumi/pkg/backend/httpstate/backend.go:766

github.com/pulumi/pulumi/pkg/backend/httpstate.(*cloudBackend).Preview

	/home/travis/gopath/src/github.com/pulumi/pulumi/pkg/backend/httpstate/backend.go:652

github.com/pulumi/pulumi/pkg/backend.PreviewStack

	/home/travis/gopath/src/github.com/pulumi/pulumi/pkg/backend/stack.go:68

github.com/pulumi/pulumi/pkg/backend/httpstate.(*cloudStack).Preview

	/home/travis/gopath/src/github.com/pulumi/pulumi/pkg/backend/httpstate/stack.go:131

github.com/pulumi/pulumi/cmd.newPreviewCmd.func1

	/home/travis/gopath/src/github.com/pulumi/pulumi/cmd/preview.go:93

github.com/pulumi/pulumi/pkg/util/cmdutil.RunFunc.func1

	/home/travis/gopath/src/github.com/pulumi/pulumi/pkg/util/cmdutil/exit.go:92

github.com/pulumi/pulumi/vendor/github.com/spf13/cobra.(*Command).execute

	/home/travis/gopath/src/github.com/pulumi/pulumi/vendor/github.com/spf13/cobra/command.go:702

github.com/pulumi/pulumi/vendor/github.com/spf13/cobra.(*Command).ExecuteC

	/home/travis/gopath/src/github.com/pulumi/pulumi/vendor/github.com/spf13/cobra/command.go:783

github.com/pulumi/pulumi/vendor/github.com/spf13/cobra.(*Command).Execute

	/home/travis/gopath/src/github.com/pulumi/pulumi/vendor/github.com/spf13/cobra/command.go:736

main.main

	/home/travis/gopath/src/github.com/pulumi/pulumi/main.go:49

runtime.main

	/home/travis/.gimme/versions/go1.11.linux.amd64/src/runtime/proc.go:201

runtime.goexit

	/home/travis/.gimme/versions/go1.11.linux.amd64/src/runtime/asm_amd64.s:1333
```

**Comment by swgillespie** [comment] 2019-03-11 21:15
I'm having trouble coming up with a sequence of steps that reproduces this issue. Can anyone that has run into this issue provide 1) a set of steps that got their machine into a bad state, 2) the output of `pulumi plugin ls`, and 3) the output of `pulumi preview --logtostderr -v 7`?

In terms of anecdotal evidence, @timmyers has been using Yarn - @oliverholliday are you also using Yarn and/or did you use Yarn to upgrade the offending azure package?

**Comment by geekflyer** [comment] 2019-03-11 23:37
@swgillespie I also hit this issue a few minutes ago. In an attempt to resolve it I deleted node_modules ~/.pulumi, upgraded all dependencies and reinstalled pulumi from scratch. None if this helped.  What actually eventually helped was running once PULUMI_ENABLE_LEGACY_PLUGIN_SEARCH=1 pulumi up  and after that the issue didn't appear anymore, even if not setting PULUMI_ENABLE_LEGACY_PLUGIN_SEARCH. This leads me to believe that the issue only occurs with a certain state in the stack. Perhaps this only occurs if there are some resources with an older pulumi provider version in the stack?

**Comment by geekflyer** [comment] 2019-03-11 23:42
If you can tell me if and how I can recover a certain snapshot of a stack I probably can "rollback" to the state where this issue occured and help reproducing this.

**Comment by swgillespie** [comment] 2019-03-11 23:50
I'm not aware of a way to roll back to an older version of a stack, unfortunately. The fact that your stack was OK after `pulumi up` with the env var set is a super useful clue, though - thanks!

Here's what I think is going down:

1. A user initiates an upgrade via npm or yarn of a package that requires a provider plugin.
2. For whatever reason, the provider plugin is not installed by the package manager when processing (1)
3. At runtime, Pulumi requests to load a package whose version matches the one acquired by npm/yarn, except that the plugin was never installed and we see this error.

The reason why `PULUMI_ENABLE_LEGACY_PLUGIN_SEARCH` works is because it modifies step (3) to be much more lenient about which plugin it loads. It accepts a newer plugin than the one that is requested, which appears to fix the issue.

The combination of that and step (2) implies to me that a plugin *did* get installed in step (2), but it was *newer* than what step (3) was expecting, so I'll keep investigating on that front.

**Comment by adaniline-traderev** [comment] 2019-03-12 13:38
I have the same issue when running on Jenkins:
`yarn install` does not install any plugins under `~/.pulumi`, and `pulumi up` gives an error

**Comment by swgillespie** [comment] 2019-03-12 17:24
Thanks to @adaniline-traderev's example on slack (thank you!) I had a moment of inspiration and here's what's going on here and here is a set of repro steps.

1. Start with this program:

```typescript
import * as aws from "@pulumi/aws";

const b = new aws.s3.Bucket("bucket");
export const name = b.id;
```


```
{
    "name": "aws-typescript",
    "devDependencies": {
        "@types/node": "latest"
    },
    "dependencies": {
        "@pulumi/pulumi": "0.17.0",
        "@pulumi/aws": "0.17.0"
    }
}
```

2. Create a stack and initialize config:

```
$ pulumi stack init dev
Created stack 'dev'
$ pulumi config set aws:region us-west-2
```

3.  yarn install

```
$ yarn install
warning package.json: No license field
info No lockfile found.
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
warning aws-typescript: No license field
[1/4] 🔍   Resolving packages...
[2/4] 🚚   Fetching packages...
[3/4] 🔗   Linking dependencies...
[4/4] 🔨   Building fresh packages...
success Saved lockfile.
✨  Done in 16.38s.
```

4. Observe that a plugin did get installed, at version 0.17.0

```
$ pulumi plugin ls
NAME  KIND      VERSION  SIZE    INSTALLED       LAST USED
aws   resource  0.17.0   156 MB  28 seconds ago  28 seconds ago

TOTAL plugin cache size: 156 MB
```

5. Pulumi update:

```
▶ pulumi update
Previewing update (dev):

     Type                 Name      Plan
 +   pulumi:pulumi:Stack  node-dev  create
 +   └─ aws:s3:Bucket     bucket    create

Resources:
    + 2 to create

Do you want to perform this update? yes
Updating (dev):

     Type                 Name      Status
 +   pulumi:pulumi:Stack  node-dev  created
 +   └─ aws:s3:Bucket     bucket    created

Outputs:
    name: "bucket-4d0d87a"

Resources:
    + 2 created

Duration: 5s

Permalink: https://app.pulumi.com/swgillespie/node/dev/updates/1
```

6. Upgrade to version 0.17.1 of `@pulumi/pulumi` and `@pulumi/aws`:

```diff
7,8c7,8
<         "@pulumi/aws": "0.17.0",
<         "@pulumi/pulumi": "0.17.0"
---
>         "@pulumi/aws": "0.17.1",
>         "@pulumi/pulumi": "0.17.1"
```

```
$ yarn install
```

7. Observe that yarn installed v0.17.1 of the aws plugin:

```
NAME  KIND      VERSION  SIZE    INSTALLED       LAST USED
aws   resource  0.17.1   156 MB  24 seconds ago  24 seconds ago
aws   resource  0.17.0   156 MB  3 minutes ago   now

TOTAL plugin cache size: 312 MB
```

8. Pulumi update

```
$ pulumi update
Previewing update (dev):

     Type                 Name      Plan
     pulumi:pulumi:Stack  node-dev

Resources:
    2 unchanged

Do you want to perform this update? yes
Updating (dev):

     Type                 Name      Status
     pulumi:pulumi:Stack  node-dev

Outputs:
    name: "bucket-4d0d87a"

Resources:
    2 unchanged

Duration: 2s

Permalink: https://app.pulumi.com/swgillespie/node/dev/updates/2
```

9. Verify that v0.17.1 of the aws provider is in the snapshot:

```
$ pulumi stack export | jq '.deployment.resources[1].inputs.version'
"0.17.1"
```

10. Downgrade back to v0.17.0 of the aws and pulumi packages:

```diff
7,8c7,8
<         "@pulumi/aws": "0.17.1",
<         "@pulumi/pulumi": "0.17.1"
---
>         "@pulumi/aws": "0.17.0",
>         "@pulumi/pulumi": "0.17.0"
```

11. Delete all plugins:

```
$ pulumi plugin rm --all
```

12. Yarn install

```
$ yarn install
yarn install v1.13.0
warning package.json: No license field
warning aws-typescript: No license field
[1/4] 🔍   Resolving packages...
[2/4] 🚚   Fetching packages...
[3/4] 🔗   Linking dependencies...
[4/4] 🔨   Building fresh packages...
✨  Done in 16.56s.
```

13. The program is now hosed:

```
$ pulumi preview
Previewing update (dev):
Permalink: https://app.pulumi.com/swgillespie/node/dev/previews/6d827635-014d-44d1-8a62-8347261d5b65
error: could not load plugin for aws provider 'urn:pulumi:dev::node::pulumi:providers:aws::default': no resource plugin 'aws-v0.17.1' found in the workspace or on your $PATH, install the plugin using `pulumi plugin install resource aws v0.17.1`
```

14. Observe that running `pulumi plugin install` does not help:

```
$ pulumi plugin install --verbose
[resource plugin aws-0.17.0] installing
[resource plugin aws-0.17.0] skipping install (existing >= match)

$ pulumi preview
Previewing update (dev):
Permalink: https://app.pulumi.com/swgillespie/node/dev/previews/3041658b-f5b0-4886-a7b1-3ab6090865fc
error: could not load plugin for aws provider 'urn:pulumi:dev::node::pulumi:providers:aws::default': no resource plugin 'aws-v0.17.1' found in the workspace or on your $PATH, install the plugin using `pulumi plugin install resource aws v0.17.1`
```

I believe this repro covers everyone that's posted about having issues in this thread. Step 11 and step 12 simulate being in CI environments, which is why I believe that everyone has seen this trouble in their CI environments while observing that they have no problems when run locally.

## Workaround

If you are in this situation, you can run the command present in the error message and it will install the missing plugin:

```
$ pulumi plugin install resource aws v0.17.1
[resource plugin aws-0.17.1] installing
Downloading plugin:  43.14 MiB / 43.14 MiB [========================] 100.00% 9s


$ pulumi preview
Previewing update (dev):

     Type                 Name      Plan
     pulumi:pulumi:Stack  node-dev

Resources:
    2 unchanged

Permalink: https://app.pulumi.com/swgillespie/node/dev/previews/f8573b59-bc59-4fa8-ade7-9ee17d4d1d1c
```

Given that this most often happens in CI scenarios, a reasonable workaround for now would be to put this command in your CI script until Pulumi delivers a fix.

**Comment by swgillespie** [comment] 2019-03-12 17:26
Also worth noting is that, although this bug masqueraded as an issue with our new plugin load behavior (and `PULUMI_ENABLE_LEGACY_PLUGIN_SEARCH`), this is actually not a new bug and both the old and new plugin loading behaviors are equally broken.

**Comment by oliverholliday** [comment] 2019-03-12 17:30
Nice one

**Comment by lukehoban** [comment] 2019-03-16 18:01
This is fixed with https://github.com/pulumi/pulumi/pull/2560 which is part of the `0.17.2` release.

**Closed by lukehoban** 2019-03-16 18:01 UTC
Labels: priority/P1
