### ISSUE TITLE
Missing file fails install (python)

### ISSUE THREAD

**Issue by slikk66** [pulumi/pulumi-azure#132] opened 2018-10-08 17:57 UTC
https://github.com/pulumi/pulumi-azure/blob/master/sdk/python/setup.py#L14

```
    Traceback (most recent call last):                                                                                                                                                                       
      File "<string>", line 1, in <module>                                                                                                                                                                   
      File "/Users/user/Development/pulumi/pulumi-azure/sdk/python/setup.py", line 20, in <module>                                                                                                       
        long_description=readme(),                                                                                                                                                                           
      File "/Users/user/Development/pulumi/pulumi-azure/sdk/python/setup.py", line 14, in readme                                                                                                         
        with open('README.rst') as f:                                                                                                                                                                        
    IOError: [Errno 2] No such file or directory: 'README.rst'   
```

Also, looks like you need to push a new pypi version, I'm still seeing role.assignment.assignment instead of role.assignment.Assignment

I'd be willing to push a PR for this fix, but it seems maybe it should be fixed in the tfgen repo instead?  Seems the setup is generated also by tfgen, should dump a README.rst in the folder if so.

**Comment by CyrusNajmabadi** [comment] 2018-10-09 16:44
@lukehoban I know nothing about python :)   I can try to figure out what's going on here, but maybe someone else might be better to start with?  @swgillespie do you know anything about the above?

**Comment by swgillespie** [comment] 2018-10-09 16:56
> I'd be willing to push a PR for this fix, but it seems maybe it should be fixed in the tfgen repo instead? 

Thank you! Yeah, the fix for this will be in tfgen, which autogenerates all of the Python in this repo. @ellismg do you think we'd be able to re-use the pandoc stuff for generating `README.rst` from our markdown?

**Comment by dbilleci-lightstream** [comment] 2018-10-11 15:31
Looked at the code, I could either wrap the open('README') with a try/except in setup.py, or I can see where a good place for this README.rst should come from and try to create one?

**Comment by dbilleci-lightstream** [comment] 2018-10-11 15:33
Actually, none of the other packages have a README file either, maybe we should just change it to read VERSION instead and call it a day?

**Comment by slikk66** [comment] 2018-10-11 15:44
switched back to my personal acct for the PR - https://github.com/pulumi/pulumi-terraform/pull/264

**Comment by ellismg** [comment] 2018-10-11 15:59
> @ellismg do you think we'd be able to re-use the pandoc stuff for generating README.rst from our markdown?

I’ll admit I’m confused.  The README.rst is generated as part of running `make build` when pandoc is installed and when pandoc is not installed, we generate an empty one. In what case are we running into the above error?  Is a package we published to PiPy just wrong, or is this happening when trying to build locally in some configuration?

Perhaps we should just switch to a model where we generate and check in the README.rst file into the source tree?  We could do validation in CI such that it and README.md don’t get out of date (since we know we can always have Pandoc in CI).

The proposal to use VERSION instead feels wrong. I think it will be the description shown on PyPi will just be a very number instead of a nicer description of the library.

**Comment by ellismg** [comment] 2018-10-30 18:49
@swgillespie it's still not clear to me there's an issue here.  The only think I can think of is that since the README.rst is generated by the build, on a fresh clone it wouldn't be present, and so trying to pip install the source directly could fail.

We could check in the README.rst's if we preferred and just have the build update them when `pandoc` is installed.  At some point, I imagine we end up forking the README's between the node and python versions of the packages anyway.

I have not been able to reproduce an issue where the package fails to install for any of our packages on PyPI.

**Comment by dbilleci-lightstream** [comment] 2018-10-31 15:40
The original issue was from trying to pip install directly from the github repo (which should be allowed, I think in normal circumstances) but perhaps it doesn't line up with your intended workflow.

I was trying to get around the role.assignment -> role.Assignment issue that was here a few versions back, PyPi was behind, but Github repo had the fix, which led me to try and install from the repo using similar to this syntax and encountering the error:
````
-e git://github.com/pulumi/pulumi-azure.git#egg=pulumi-azure
````

**Comment by swgillespie** [comment] 2018-11-01 21:32
> The original issue was from trying to pip install directly from the github repo (which should be allowed, I think in normal circumstances) but perhaps it doesn't line up with your intended workflow.

Oh! Yeah, so you'll need to point `pip install` at the `sdk/pulumi/bin` subdirectory and not `sdk/pulumi`. As part of the build, we generate some files (including README.rst) and produce a package in `sdk/pulumi/bin`, which is ultimately the thing we upload to PyPI. If you want to install the package yourself, you have to do a build of this repo and then `pip install` that subdirectory.

Can you try that and see if that works for you?

**Closed** 2018-11-09 19:38 UTC
