### ISSUE TITLE
WindowsFunctionApp with existing AppServicePlans

### ISSUE THREAD

**Issue by ranjeetkpGit** [pulumi/pulumi-azure#1922] opened 2024-03-29 15:19 UTC
Hi,
We have existing AppServicePlans created with AppServicePlan(Native) and Plan (Classic) components but when referencing them in WindowsFunctionApp, getting following error. WindowsFunctionApp expects 'serverFarms' (We get serverFarms when creating new plans using ServicePlan component)
but we get 'serverfarms' from existing AppServicePlans
Is there any way we can create WindowsFunctionApp with existing AppServicePlan ?
We are using C# and .NET 8 to create Azure resources.

![image](https://github.com/pulumi/pulumi-azure/assets/92055761/42f02778-20c9-461b-b269-7e70745d502d)

**Comment by danielrbradley** [comment] 2024-04-02 10:09
Hi @ranjeetkpGit 

Could you expand on how you're getting the value for the resource ID from Pulumi - please share some example Pulumi code if at all possible. It looks like the error you've shared is possibly from within your function app rather that from you Pulumi code.

Some resource id segments are case insensitive, and Azure sometimes returns different casing too. It's possible that the library producing this error is being overly strict, though this should also be fairly easy to work around with a string replacement if in doubt.

**Comment by ranjeetkpGit** [comment] 2024-04-02 16:24
Hi @danielrbradley ,

Thanks for reply. I am creating WindowsFunctionApp as below
  
        private WindowsFunctionApp CreateFunctionResource(string appName, Plan appServicePlan, FunctionSettings functionSettings, InputMap<string> settings = null, int maxScaleOutLimit = 0)
        {
            var name = "test-my-funcapp"
            var configurations = new InputMap<string>
            {
                { WebsiteRunFromPackage, "1" },
                { AppInsightsConnectionString, _appInsightsConnectionString},
                { LoggingEventHubConnectionString, _coreSettings.EventHubSettings.EventHubConnectionString},
                { LoggingEventHubName, _coreSettings.EventHubSettings.EventHubName },
                { LoggingIndexName, _coreSettings.EventHubSettings.LogIndexName },
                { LoggingLogLevel, _coreSettings.EventHubSettings.LogLevel }
            };

            if (settings != null)
            {
                configurations.AddRange(settings);
            }
            var funcAppArgs = new WindowsFunctionAppArgs
            {
                ResourceGroupName = _coreSettings.ResourceGroup,
                ServicePlanId = appServicePlan.Id,
                Name = name,
                FunctionsExtensionVersion = _coreSettings.Functions.ExtensionVersion,
                Identity = new WindowsFunctionAppIdentityArgs
                {
                    Type =  "SystemAssigned"
                },
                StorageAccountName = _storageAccountName,
                StorageAccountAccessKey = _storageAccountKey,
                AppSettings = configurations,
                SiteConfig = new WindowsFunctionAppSiteConfigArgs
                {
                    AlwaysOn = functionSettings.IsDedicatedPlan(),
                    AppScaleLimit = maxScaleOutLimit,
                    ApplicationStack = new WindowsFunctionAppSiteConfigApplicationStackArgs
                    {
                      DotnetVersion  = _coreSettings.Functions.DotnetFrameworkVersion, // v8.0
                      UseDotnetIsolatedRuntime = true
                    }
                }
            };
            var functionApp = new WindowsFunctionApp($"{name}", funcAppArgs);
            return functionApp;
        }
        private Plan CreateAppServicePlan(FunctionSettings functionSettings, string appName)
        {
            var planName = "test-plan"

            var appServicePlan = new Plan(planName, new PlanArgs
            {
                Location = _coreSettings.Region,
                ResourceGroupName = _coreSettings.ResourceGroup,
                Kind = "FunctionApp",
                Name = planName,
                Sku = new PlanSkuArgs
                {
                    Tier = functionSettings.SkuTier,
                    Size = functionSettings.SkuName   // Consumption Plan
                }
            });
            return appServicePlan;
        }
        
        
![image](https://github.com/pulumi/pulumi-azure/assets/92055761/1c81682b-0e78-4307-802c-21c467d38963)

**Comment by ranjeetkpGit** [comment] 2024-04-22 19:34
> Hi @ranjeetkpGit! This issue may have been fixed in the latest provider version, see [this upstream issue](https://github.com/hashicorp/terraform-provider-azurerm/issues/24560). Could you try upgrading Azure Classic to v5.72.0?

Hi @thomas11 Thanks for reply. As FunctionApp (classic) supports till .NET 6 only, Is there any way we can upgrade it to WindowsFunctionApp without deleting existing resources?

**Comment by thomas11** [comment] 2024-04-23 05:46
> > Hi @ranjeetkpGit! This issue may have been fixed in the latest provider version, see [this upstream issue](https://github.com/hashicorp/terraform-provider-azurerm/issues/24560). Could you try upgrading Azure Classic to v5.72.0?
> 
> Hi @thomas11 Thanks for reply. As FunctionApp (classic) supports till .NET 6 only, Is there any way we can upgrade it to WindowsFunctionApp without deleting existing resources?

Hi @ranjeetkpGit, the issue title and your code sample show that you're already using WindowsFunctionApp. Is that not correct?

**Comment by ranjeetkpGit** [comment] 2024-04-23 05:52
@thomas11, This code is to upgrade existing FunctionApp (created with FunctionApp (.NET 6)) to .NET 8 using WindowsFunctionApp

**Comment by thomas11** [comment] 2024-04-23 07:04
In see. Could you try upgrading Azure Classic to v5.72.0? Or is there an issue preventing that?

**Comment by ranjeetkpGit** [comment] 2024-04-23 10:26
> In see. Could you try upgrading Azure Classic to v5.72.0? Or is there an issue preventing that?
Upgraded Azure classic to v5.73.0 
AppServicePlan case issue resolved 
but getting same issue when upgrading 
![image](https://github.com/pulumi/pulumi-azure/assets/92055761/7b9a5e02-3036-4aac-909a-803a4b137c77)

**Comment by thomas11** [comment] 2024-04-23 17:39
I'm not familiar with this specific case, but after changing your code from FunctionApp to WindowsFunctionApp, you probably need to run [`pulumi refresh`](https://www.pulumi.com/docs/cli/commands/pulumi_refresh/). This will add the existing app to your Pulumi state.

If that's not sufficient, you'll need to [import](https://www.pulumi.com/docs/cli/commands/pulumi_import/) the app via its Azure id that you can find in the Azure portal.

**Comment by thomas11** [comment] 2024-05-10 10:09
@pierskarsenbarg do you happen to have a full repro? I think I know how to fix it but cannot verify the fix without a bunch of manual setup.

**Comment by pierskarsenbarg** [comment] 2024-05-10 10:17
I've got the code for it... let me put a repo together that you can just clone and work with

**Comment by pierskarsenbarg** [comment] 2024-05-10 10:33
@thomas11 do you have a preference for language? I have it set up in c# but I can translate to typescript is that's better? (I don't think it'll matter either way for what you want to do)

**Comment by pierskarsenbarg** [comment] 2024-05-10 11:45
I can't replicate this anymore. I'm not sure why. Trying v5.73.0 (which was probably the version I was on when I tried it) as well as v5.68.0 which is what the customer seemed to be on.

Let me go back to the customer and see if this is still an issue

**Comment by mjeffryes** [comment] 2024-06-11 19:09
@pierskarsenbarg any update here on whether the customer is still seeing this issue?

**Comment by mjeffryes** [comment] 2024-06-24 23:16
closing for now since we can seem to find a program to reproduce

**Closed by mjeffryes** 2024-06-24 23:16 UTC
Labels: kind/enhancement, resolution/no-repro, awaiting-feedback
