### ISSUE TITLE
Errors when destroying Service Principal Passwords - azuread

### ISSUE THREAD

**Issue by pjoe** [pulumi/pulumi-azure#599] opened 2020-06-11 17:26 UTC
Seeing weird errors when destroying Service Principal Password:

```
Diagnostics:
  azuread:index:ServicePrincipalPassword (k8s-dev-SpPassword-ExtDNS):
    error: deleting urn:pulumi:k8s::tms-pulumi::azuread:index/servicePrincipalPassword:ServicePrincipalPassword::k8s-dev-SpPassword-ExtDNS: Error parsing Application Password ID: Credential ID should be in 
the format {objectId}/{keyType}/{keyId} - but got "f0aad1c4-****-4629-929e-b4f2da41****/33ee0852-****-****-17d0-33b52a02****"
```

This happened with:
- pulumi: 2.4.0
- pulumi/azure: 3.8.0
- pulumi/azuread: 2.3.0

I tried downgrading a couple of versions but got same error.

In the end I had to export the stack, remove in the json and then import.

I have earlier successfully destroyed stacks with SpPasswords, so guessing something must have changed.

**Comment by mikhailshilkov** [comment] 2020-06-15 11:37
It sounds like a consequence of https://github.com/terraform-providers/terraform-provider-azuread/pull/264

Does it work if you create this resource again with the newest version, and then delete it?

**Comment by mikhailshilkov** [comment] 2023-08-07 12:53
As mentioned above, I assume the problem was caused by a breaking change between two old versions. Since no comments were posted since 2020, I'll go ahead and close the issue as resolved.

**Closed by mikhailshilkov** 2023-08-07 12:53 UTC
Labels: kind/bug, resolution/fixed
