### ISSUE TITLE
CORS settings not synchronized in AppService after update

### ISSUE THREAD

**Issue by dokuboyejo** [pulumi/pulumi-azure#564] opened 2020-05-12 05:54 UTC
Some settings such as CORS do not get to be removed even after removing from configs
So, if an app service is created with a site config such as below
```
site_config:
            alwaysOn: true
            cors:
              allowedOrigins:
              - https://www.domain.com
              supportCredentials: true
            dotnetFrameworkVersion: v4.0
            ftps_state: FtpsOnly
```

Modifying the CORS setting of the app service by removing enries from config doesn't get synchronized
```
site_config:
            alwaysOn: true
            dotnetFrameworkVersion: v4.0
            ftps_state: FtpsOnly
```

**Comment by leezen** [comment] 2020-05-12 17:36
Could you please clarify what you're doing a bit more? Is the above YAML config you're reading and then setting in an app service? What does your code look like? When you say it doesn't get synchronized, what does the diff from `pulumi up` show?

**Comment by dokuboyejo** [comment] 2020-05-12 18:32
@leezen I'm trying to update the app service settings.
Yes, I read from the yaml and try to use it to update app service.
So, the issue is creation of the cors settings works ok, but not the removal. If an app service doesn't have cors, and you set it, that works ok. If the settings are removed from the yaml, the cors doesn't get updated automatically.
code looks like below
```
app_service = appservice.AppService(
    config_resource_groups['mmazzapprg04']['application_service']['name'],
    name=config_resource_groups['mmazzapprg04']['application_service']['name'],
    resource_group_name=mmazzapprg04.name,
    app_service_plan_id=app_service_plan.id,
    enabled=config_resource_groups['mmazzapprg04']['application_service']['enabled'],
    https_only=config_resource_groups['mmazzapprg04']['application_service']['https_only'],
    location=config_data['location'],
    app_settings=app_settings,
    connection_strings=[
        config_resource_groups['mmazzapprg04']['sql_server']['db']['connection']
    ],
    site_config=config_resource_groups['mmazzapprg04']['application_service']['site_config'],
    logs=config_resource_groups['mmazzapprg04']['application_service']['log_config'],
    tags=config_resource_groups['mmazzapprg04']['application_service']['tags']
)
```

**Comment by dokuboyejo** [comment] 2020-05-20 12:52
@leezen just checking if you perhaps have any feedback

**Comment by leezen** [comment] 2020-05-22 13:51
Could you please share the detailed diff you see when you perform the updates and what the code for reading in your yaml looks like?

**Comment by mikhailshilkov** [comment] 2023-08-03 13:39
The issue is more than three years old and it hasn't got any recent comments or upvotes. Since the last question wasn't asked, I'll assume the problem isn't relevant anymore and will close the issue. Please open a new issue with a repro if the problem persists.

**Closed by mikhailshilkov** 2023-08-03 13:39 UTC
Labels: kind/bug, resolution/no-repro
