### ISSUE TITLE
Pulumi - error with Azure Plugin v3.17+ on Windows 10 host

### ISSUE THREAD

**Issue by shawgeek** [pulumi/pulumi-azure#707] opened 2020-09-18 20:04 UTC
# An error occurs when pulumi executes the azure plugin v3.17.0+ on a Windows 10 host

## Steps To Reproduce

1. login with azure CLI
	`az login`
2. login with pulumi locally
	`pulumi login --local`
3. init a new project using a template in an empty folder
	`pulumi new azure-typescript -n issue -d issue -s issue -y`
4. preview changes
	`pulumi preview`

Expected: See preview of changes for resource group and storage account without error
Actual: Failed preview of changes with a stacktrace and error at the bottom:
> pulumi:providers:azure (default_3_20_1):
>     error: could not read plugin [C:\Users\rshaw\.pulumi\plugins\resource-azure-v3.20.1\pulumi-resource-azure.exe] stdout: EOF
[pulumi-issue-stacktrace.txt](https://github.com/pulumi/pulumi-azure/files/5247790/pulumi-issue-stacktrace.txt)

## Steps To Fix: 
1. pin @pulumi/azure to 3.16.0 by modifying the package.config
`"@pulumi/azure": "3.16.0"`
2. update packages
`yarn`
3. preview changes
`pulumi preview`

## My Local Development Environment:
I use Chocolatey to keep my tools up to date and Yarn to manage the packages.
Chocolatey: v0.10.15
Yarn v1.22.5

### I first encountered this with these versions: 
Windows: 19041.388
Pulumi: 2.3.0
NodeJS: v14.7
Azure CLI: v2.9.1

package.config (from production app):

> {
>   "name": "azure-typescript",
>   "devDependencies": {
>     "@types/node": "^8.0.0",
>     "prettier": "2.0.5"
>   },
>   "dependencies": {
>     "@pulumi/pulumi": "^2.3.0",
>     "@pulumi/azure": "^3.8.0",
>     "@pulumi/azuread": "^2.3.0",
>     "@pulumi/random": "^2.1.2"
>   }
> }

### Still happens with everything at latest as of today:
Windows: 19041.508
Pulumi: v2.10.1
NodeJS: v14.11.0
Azure CLI: v2.11.1

package.config (from sample app to reproduce)

> {
>     "name": "issue",
>     "devDependencies": {
>         "@types/node": "^10.0.0"
>     },
>     "dependencies": {
>         "@pulumi/pulumi": "^2.0.0",
>         "@pulumi/azure": "^3.0.0"
>     }
> }

to make it work, just pin @pulumi/azure to 3.16.0

> {
>     "name": "issue",
>     "devDependencies": {
>         "@types/node": "^10.0.0"
>     },
>     "dependencies": {
>         "@pulumi/pulumi": "^2.0.0",
>         "@pulumi/azure": "3.16.0"
>     }
> }

## Interesting behavior
As the system was upgrading Windows from `19041.388` to `19041.508` I tried it and it worked, so it could be a system service that is blocking it from executing correctly (or it was a fluke). As soon as the upgrade was finished and I rebooted, the error was still happening.
I disabled all anti-virus and it still fails.

**Comment by leezen** [comment] 2020-09-24 20:30
Do you mind attempting to re-acquire the plugin manually via `pulumi plugin install resource azure 3.20.1` and see if that resolves your issue?

**Comment by shawgeek** [comment] 2020-09-24 20:59
That did not resolve the issue.
I tried with the new 3.22.0 release and that plugin works. So something with the versions 3.17.0 -> 3.20.1 don't seem to work with my configuration. I confirmed this with two other co-workers following my above steps.

**Comment by shawgeek** [comment] 2021-02-05 16:55
The likely root cause was figured out during a conversation in the Pulumi Slack:
https://pulumi-community.slack.com/archives/C84L4E3N1/p1612401818293100?thread_ts=1610460979.276800&cid=C84L4E3N1
Short of it: go generating ASLR executables and Webroot AV blocking them.

**Comment by leezen** [comment] 2021-02-06 02:13
Thanks for the update. Closing as a dupe of https://github.com/pulumi/pulumi/issues/6093

**Closed by leezen** 2021-02-06 02:13 UTC
